In [50]:
#from mlflow.artifacts import download_artifacts
import pandas as pd

def pd_read_parquet_from_mlflow(
    #run_id: str, 
    artifact_path: str) -> pd.DataFrame:
    """Load a parquet file from an mlflow artifact.

    Args:
        run_id: the mlflow Run ID
        artifact_path: the relative (to the run) path to the parquet file
    
    Returns:
        pd.DataFrame of the loaded artifact
    """
    #local_path = download_artifacts(run_id=run_id, artifact_path=artifact_path)
    return pd.read_parquet(artifact_path)

#run_id = 'c65b6c792ff240d9a2a415dbca52e4e2'
# path = 'data.parquet'
# df = pd_read_parquet_from_mlflow(path)
# df.head()
path = 'data (1).parquet'
df = pd_read_parquet_from_mlflow(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [51]:
df.shape

(6820, 158)

In [52]:
df.gender.value_counts()

gender
Woman                            2211
Man                               595
Transgender                        62
Gender Queer Or Nonconforming      51
Decline                             6
Name: count, dtype: Int64

In [53]:
df.sex.value_counts()

sex
Female    4575
Male      1792
Other        9
Name: count, dtype: Int64

In [54]:
df.user_id.nunique()

1170

In [55]:
df.sex.value_counts()

sex
Female    4575
Male      1792
Other        9
Name: count, dtype: Int64

In [56]:
female = df[df['sex'] == 'Female']['user_id'].nunique()
female

800

In [57]:
male = df[df['sex'] == 'Male']['user_id'].nunique()
male

286

In [58]:
df[df['sex'] == 'Male']['user_id'].count()

1792

In [59]:
df[df['sex'] == 'Other'][['user_id', 'sex']]

                                            user_id    sex
606  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
615  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
625  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
637  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
650  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
662  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
671  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
680  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other
689  us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963  Other

In [60]:
others = df[df['sex'] == 'Other']['user_id'].nunique()
others

1

In [66]:
a = df[ df['sex'].isna() == True][['user_id', 'sex', 'deployment']]
a.deployment.value_counts()

deployment
hr-internal-1    339
hr-rct-cue-1      41
hr-rct-ctrl-1     35
hr-uchealth-1     29
Name: count, dtype: int64

In [62]:
a= df[ df['sex'].isna() == True][['user_id', 'sex']]
a.user_id.nunique()

132

In [63]:
1170-132

1038

In [64]:
nul = df[df['sex'] == '<NA>']
nul

Empty DataFrame
Columns: [user_id, ts, active_time_m7, active_time_m14, active_time_s7, active_time_s14, activity_percent_m7, activity_percent_m14, activity_percent_s7, activity_percent_s14, chronotype_score_m7, chronotype_score_m14, chronotype_score_s7, chronotype_score_s14, display_events_m7, display_events_m14, display_events_s7, display_events_s14, ec_Activity_m7, ec_Activity_m14, ec_Activity_s7, ec_Activity_s14, ec_DeviceDisplayStatus_m7, ec_DeviceDisplayStatus_m14, ec_DeviceDisplayStatus_s7, ec_DeviceDisplayStatus_s14, ec_Location_m7, ec_Location_m14, ec_Location_s7, ec_Location_s14, ec_PedometerData_m7, ec_PedometerData_m14, ec_PedometerData_s7, ec_PedometerData_s14, ec_total_m7, ec_total_m14, ec_total_s7, ec_total_s14, time_at_location_1_m7, time_at_location_1_m14, time_at_location_1_s7, time_at_location_1_s14, time_at_location_2_m7, time_at_location_2_m14, time_at_location_2_s7, time_at_location_2_s14, time_at_location_3_m7, time_at_location_3_m14, time_at_location_3_s7, time_at_location_3_s14, time_at_location_4_m7, time_at_location_4_m14, time_at_location_4_s7, time_at_location_4_s14, time_at_location_5_m7, time_at_location_5_m14, time_at_location_5_s7, time_at_location_5_s14, num_location_clusters_m7, num_location_clusters_m14, num_location_clusters_s7, num_location_clusters_s14, steps_least_active_5h_m7, steps_least_active_5h_m14, steps_least_active_5h_s7, steps_least_active_5h_s14, loc_entropy_m7, loc_entropy_m14, loc_entropy_s7, loc_entropy_s14, screen_unlocks_m7, screen_unlocks_m14, screen_unlocks_s7, screen_unlocks_s14, sleep_duration_m7, sleep_duration_m14, sleep_duration_s7, sleep_duration_s14, sleep_end_m7, sleep_end_m14, sleep_end_s7, sleep_end_s14, sleep_interruptions_m7, sleep_interruptions_m14, sleep_interruptions_s7, sleep_interruptions_s14, sleep_start_m7, sleep_start_m14, sleep_start_s7, sleep_start_s14, steps_most_active_10h_m7, steps_most_active_10h_m14, steps_most_active_10h_s7, steps_most_active_10h_s14, steps_relative_amplitude_m7, steps_relative_amplitude_m14, steps_relative_amplitude_s7, steps_relative_amplitude_s14, sleep_routine_index_m7, sleep_routine_index_m14, ...]
Index: []

[0 rows x 158 columns]

In [65]:
df[df['sex'] == 'Other']['user_id']

606    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
615    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
625    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
637    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
650    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
662    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
671    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
680    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
689    us-east-1:67c6de8a-a97b-4a6c-9394-e5c634c1a963
Name: user_id, dtype: object

In [47]:
df.user_id.unique()

array(['us-east-1:1b087523-b47b-421c-97c4-74da80564598',
       'us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b',
       'us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684', ...,
       'us-east-1:db841a21-c42d-c6b4-cef4-927eab17ce65',
       'us-east-1:db841a21-c452-c3d4-f82c-773d4ed8805f',
       'us-east-1:db841a21-c469-cee5-525d-e2e262014c84'], dtype=object)

In [69]:
df.user_id.unique()

array(['us-east-1:1b087523-b47b-421c-97c4-74da80564598',
       'us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b',
       'us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684', ...,
       'us-east-1:db841a21-c42d-c6b4-cef4-927eab17ce65',
       'us-east-1:db841a21-c452-c3d4-f82c-773d4ed8805f',
       'us-east-1:db841a21-c469-cee5-525d-e2e262014c84'], dtype=object)

In [ ]:
male +female+ others

1087

In [49]:
a = df[['user_id', 'sex']].drop_duplicates()
a.sex.value_counts()

sex
Female    800
Male      286
Other       1
Name: count, dtype: Int64

In [50]:
a.isna().sum()

user_id      0
sex        132
dtype: int64

In [11]:
total_user=df.groupby('user_id').count()

In [14]:
total_user.shape

(1170, 157)

In [15]:
total_user.sex.value_counts()

sex
6     328
1     135
7     109
0      83
3      83
4      81
5      81
2      80
9      67
8      46
10     20
13      9
11      8
14      5
12      4
15      4
28      3
18      3
22      2
31      2
25      2
21      2
59      2
20      1
16      1
17      1
49      1
23      1
32      1
60      1
19      1
52      1
36      1
40      1
Name: count, dtype: int64

In [15]:
#from mlflow.artifacts import download_artifacts
import pandas as pd

def pd_read_parquet_from_mlflow(
    #run_id: str, 
    artifact_path: str) -> pd.DataFrame:
    """Load a parquet file from an mlflow artifact.

    Args:
        run_id: the mlflow Run ID
        artifact_path: the relative (to the run) path to the parquet file
    
    Returns:
        pd.DataFrame of the loaded artifact
    """
    #local_path = download_artifacts(run_id=run_id, artifact_path=artifact_path)
    return pd.read_parquet(artifact_path)

#run_id = 'c65b6c792ff240d9a2a415dbca52e4e2'
# path = 'data.parquet'
# df = pd_read_parquet_from_mlflow(path)
# df.head()
path = 'data (1).parquet'
df = pd_read_parquet_from_mlflow(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [16]:
df.shape

(6820, 158)

In [17]:
new_df = df[['user_id','sex']]
new_df

                                             user_id     sex
0     us-east-1:1b087523-b47b-421c-97c4-74da80564598    Male
1     us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b  Female
2     us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684  Female
3     us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d  Female
4     us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8    Male
...                                              ...     ...
1507  us-east-1:db841a21-c452-c3d4-f82c-773d4ed8805f  Female
1508  us-east-1:db841a21-c447-c546-5505-f39437315109  Female
1509  us-east-1:db841a21-c4f8-c359-4d5c-97de2759e13b  Female
1510  us-east-1:db841a21-c469-cee5-525d-e2e262014c84  Female
1511  us-east-1:db841a21-c4f8-c359-4d5c-97de2759e13b  Female

[6820 rows x 2 columns]

In [18]:
new_df.shape

(6820, 2)

In [85]:
df_unique = new_df.drop_duplicates(subset='user_id').dropna()
df_unique

                                             user_id     sex
0     us-east-1:1b087523-b47b-421c-97c4-74da80564598    Male
1     us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b  Female
2     us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684  Female
3     us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d  Female
4     us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8    Male
...                                              ...     ...
1486  us-east-1:db841a21-c452-ca34-7b0f-afa1b66d0acd  Female
1495  us-east-1:db841a21-c401-cd75-d72d-214961de714d  Female
1501  us-east-1:db841a21-c42d-c6b4-cef4-927eab17ce65  Female
1507  us-east-1:db841a21-c452-c3d4-f82c-773d4ed8805f  Female
1510  us-east-1:db841a21-c469-cee5-525d-e2e262014c84  Female

[1038 rows x 2 columns]

In [79]:
sex_counts = df_unique['sex'].value_counts()
sex_counts

sex
Female    765
Male      272
Other       1
Name: count, dtype: Int64

In [83]:
765+272+1 -1170

-132

In [81]:
sex_percentages = (sex_counts / len(df_unique)) * 100
sex_percentages = sex_percentages.round(2)
sex_percentages

sex
Female    65.38
Male      23.25
Other      0.09
Name: count, dtype: Float64

In [14]:
#from mlflow.artifacts import download_artifacts
import pandas as pd

def pd_read_parquet_from_mlflow(
    #run_id: str, 
    artifact_path: str) -> pd.DataFrame:
    """Load a parquet file from an mlflow artifact.

    Args:
        run_id: the mlflow Run ID
        artifact_path: the relative (to the run) path to the parquet file
    
    Returns:
        pd.DataFrame of the loaded artifact
    """
    #local_path = download_artifacts(run_id=run_id, artifact_path=artifact_path)
    return pd.read_parquet(artifact_path)

#run_id = 'c65b6c792ff240d9a2a415dbca52e4e2'
# path = 'data.parquet'
# df = pd_read_parquet_from_mlflow(path)
# df.head()
path = 'data (1).parquet'
df = pd_read_parquet_from_mlflow(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [15]:
df = df[df.deployment == 'hr-ascent-1']
df.shape

(2924, 158)

In [16]:
new_df = df[['user_id','sex']]
new_df

                                             user_id     sex
0     us-east-1:db841a21-c4fd-cf09-4379-5af0b6185e0e  Female
1     us-east-1:db841a21-c48b-cd1c-563f-eb23aa6c2768  Female
2     us-east-1:db841a21-c46a-c6fd-ca13-1faabac2c46d  Female
3     us-east-1:db841a21-c4b2-c6b9-91ed-370b2da2aa86  Female
4     us-east-1:db841a21-c438-c76a-5078-c47a75e6b0c3  Female
...                                              ...     ...
2919  us-east-1:db841a21-c47e-cfab-1ebe-8283ed8dfd96    Male
2920  us-east-1:db841a21-c4ab-c3d3-ee67-70a06f76ac36  Female
2921  us-east-1:db841a21-c463-c00d-fbe0-780c388ba581    Male
2922  us-east-1:db841a21-c47d-c6e9-48da-980b0f23abef  Female
2923  us-east-1:db841a21-c439-ca52-2cde-e7da3aee42b3  Female

[2924 rows x 2 columns]

In [17]:
new_df[ new_df['sex'].isna() == True][['user_id', 'sex']]

Empty DataFrame
Columns: [user_id, sex]
Index: []

In [14]:
new_df.sex.value_counts()

sex
Female    2314
Male       610
Name: count, dtype: Int64

In [18]:
2314+610

2924

In [28]:
new_df[(new_df['sex']!='Male') | (new_df['sex']!='Female')]

                                             user_id     sex
0     us-east-1:db841a21-c4fd-cf09-4379-5af0b6185e0e  Female
1     us-east-1:db841a21-c48b-cd1c-563f-eb23aa6c2768  Female
2     us-east-1:db841a21-c46a-c6fd-ca13-1faabac2c46d  Female
3     us-east-1:db841a21-c4b2-c6b9-91ed-370b2da2aa86  Female
4     us-east-1:db841a21-c438-c76a-5078-c47a75e6b0c3  Female
...                                              ...     ...
2919  us-east-1:db841a21-c47e-cfab-1ebe-8283ed8dfd96    Male
2920  us-east-1:db841a21-c4ab-c3d3-ee67-70a06f76ac36  Female
2921  us-east-1:db841a21-c463-c00d-fbe0-780c388ba581    Male
2922  us-east-1:db841a21-c47d-c6e9-48da-980b0f23abef  Female
2923  us-east-1:db841a21-c439-ca52-2cde-e7da3aee42b3  Female

[2924 rows x 2 columns]

In [ ]:
new_df = df[['user_id','sex']]
df_unique = new_df.drop_duplicates(subset='user_id').dropna()
sex_counts = df_unique['sex'].value_counts()
sex_percentages = (sex_counts / len(df_unique)) * 100
sex_percentages = sex_percentages.round(2)

In [ ]:
df_unique = new_df.drop_duplicates(subset='user_id').dropna()
df_unique

                                             user_id     sex
0     us-east-1:db841a21-c4fd-cf09-4379-5af0b6185e0e  Female
1     us-east-1:db841a21-c48b-cd1c-563f-eb23aa6c2768  Female
2     us-east-1:db841a21-c46a-c6fd-ca13-1faabac2c46d  Female
3     us-east-1:db841a21-c4b2-c6b9-91ed-370b2da2aa86  Female
4     us-east-1:db841a21-c438-c76a-5078-c47a75e6b0c3  Female
...                                              ...     ...
2123  us-east-1:db841a21-c463-c00d-fbe0-780c388ba581    Male
2177  us-east-1:db841a21-c410-cf92-a396-85539744f102  Female
2491  us-east-1:db841a21-c4e4-caff-f70d-e83641dc981d  Female
2665  us-east-1:db841a21-c47d-c6e9-48da-980b0f23abef  Female
2796  us-east-1:db841a21-c40f-c8a8-a41e-d47ce3fe7e82    Male

[601 rows x 2 columns]

In [102]:
sex_counts = df_unique['sex'].value_counts()
sex_counts

sex
Female    474
Male      127
Name: count, dtype: Int64

In [92]:
474 +127

601

In [103]:
sex_percentages = (sex_counts / len(df_unique)) * 100
sex_percentages = sex_percentages.round(2)
sex_percentages

sex
Female    78.87
Male      21.13
Name: count, dtype: Float64

In [105]:

def pd_read_parquet_from_mlflow(
    #run_id: str, 
    artifact_path: str) -> pd.DataFrame:
    """Load a parquet file from an mlflow artifact.

    Args:
        run_id: the mlflow Run ID
        artifact_path: the relative (to the run) path to the parquet file
    
    Returns:
        pd.DataFrame of the loaded artifact
    """
    #local_path = download_artifacts(run_id=run_id, artifact_path=artifact_path)
    return pd.read_parquet(artifact_path)

#run_id = 'c65b6c792ff240d9a2a415dbca52e4e2'
# path = 'data.parquet'
# df = pd_read_parquet_from_mlflow(path)
# df.head()
path = 'data (1).parquet'
df = pd_read_parquet_from_mlflow(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [106]:
df = df[df.deployment == 'hr-ascent-1']
df.shape

(2924, 158)

In [122]:
import pandas as pd



# Optional: if you have a ts column, sort by user and time
if 'ts' in df.columns:
    df['ts'] = pd.to_datetime(df['ts'])
    df = df.sort_values(by=['user_id', 'ts'])

# Get first and last PHQ8 score for each user
first_scores = df.groupby('user_id').first()['phq8_total']
last_scores = df.groupby('user_id').last()['phq8_total']

# Combine into a new DataFrame
phq_df_1 = pd.DataFrame({
    'phq8_before': first_scores,
    'phq8_after': last_scores
}).reset_index()

# Removing the users who have submitted just once 
counts = df.groupby('user_id')[['phq8_total']].nunique().reset_index()
counts= pd.DataFrame(counts)
counts.columns
counts= counts[counts.phq8_total == 1]
phq_df =  phq_df_1[~phq_df_1['user_id'].isin(counts['user_id'])]

# Compute change
phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']

# Categorize users
no_change = phq_df[phq_df['change'] == 0]
improved = phq_df[phq_df['change'] < 0]
declined = phq_df[phq_df['change'] > 0]

# Summary stats
total = len(phq_df)
no_change_count = len(no_change)
improved_count = len(improved)
declined_count = len(declined)

no_change_percent = round((no_change_count / total) * 100, 1)
improved_percent = round((improved_count / total) * 100, 1)
declined_percent = round((declined_count / total) * 100, 1)

avg_improvement = round(abs(improved['change'].mean()), 2) if improved_count > 0 else 0
avg_decline = round(abs(declined['change'].mean()), 2) if declined_count > 0 else 0

# Output
print(f"{no_change_count}/{total} users had no change ({no_change_percent}%)")
print(f"{improved_count}/{total} users improved ({improved_percent}%) with an average change in PHQ-8 of {avg_improvement} points")
print(f"{declined_count}/{total} users declined ({declined_percent}%) with an average change in PHQ-8 of {avg_decline} points")

52/512 users had no change (10.2%)
294/512 users improved (57.4%) with an average change in PHQ-8 of 5.26 points
166/512 users declined (32.4%) with an average change in PHQ-8 of 3.66 points

/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_4109/2670979384.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']

In [125]:
phq_df['change'].describe()

count    512.000000
mean      -1.833984
std        5.294625
min      -24.000000
25%       -5.000000
50%       -1.000000
75%        2.000000
max       16.000000
Name: change, dtype: float64

In [123]:
52+294+166

512

In [ ]:
141/601 users had no change (23.5%)
294/601 users improved (48.9%) with an average change in PHQ-8 of 5.26 points
166/601 users declined (27.6%) with an average change in PHQ-8 of 3.66 points

In [117]:
phq_df

,user_id,phq8_before,phq8_after,change
0,us-east-1:db841a21-c400-c09b-cb33-144516a80231,8.0,7.0,-1.0
1,us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268,17.0,6.0,-11.0
2,us-east-1:db841a21-c402-c83f-fadf-41f6d4271053,18.0,14.0,-4.0
3,us-east-1:db841a21-c402-c9e0-501c-45fd38e3b5e3,16.0,16.0,0.0
4,us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1,16.0,13.0,-3.0
...,...,...,...,...
596,us-east-1:db841a21-c4ff-c644-6a64-0583e73a79d9,24.0,24.0,0.0
597,us-east-1:db841a21-c4ff-c868-02a6-5cfff64a075a,8.0,7.0,-1.0
598,us-east-1:db841a21-c4ff-cb45-cad0-4821d631eb58,18.0,21.0,3.0
599,us-east-1:db841a21-c4ff-cb63-a6da-f45b3c81a5c5,5.0,0.0,-5.0
600,us-east-1:db841a21-c4ff-cf28-acdc-a8ab36af1fa3,16.0,6.0,-10.0

In [118]:
counts = df.groupby('user_id')[['phq8_total']].nunique().reset_index()
counts= pd.DataFrame(counts)
counts.columns

Index(['user_id', 'phq8_total'], dtype='object')

In [119]:
counts= counts[counts.phq8_total == 1]
counts

                                            user_id  phq8_total
3    us-east-1:db841a21-c402-c9e0-501c-45fd38e3b5e3           1
9    us-east-1:db841a21-c404-c761-77c2-8cab76aaa00a           1
12   us-east-1:db841a21-c404-cff1-369e-124fb7a439b3           1
16   us-east-1:db841a21-c406-ccf9-7dce-71496e2b0b9c           1
17   us-east-1:db841a21-c407-c0e5-a83d-7cd2cd6853b7           1
..                                              ...         ...
581  us-east-1:db841a21-c4fb-cb36-d1aa-564334701e89           1
584  us-east-1:db841a21-c4fc-cde7-6a1b-898e6a76f951           1
592  us-east-1:db841a21-c4fe-c47c-69c1-a1bc093db130           1
594  us-east-1:db841a21-c4fe-c92f-fb9c-7b7db7f224cb           1
596  us-east-1:db841a21-c4ff-c644-6a64-0583e73a79d9           1

[89 rows x 2 columns]

In [120]:
final_phq_change_df = phq_df[~phq_df['user_id'].isin(counts['user_id'])]
final_phq_change_df

,user_id,phq8_before,phq8_after,change
0,us-east-1:db841a21-c400-c09b-cb33-144516a80231,8.0,7.0,-1.0
1,us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268,17.0,6.0,-11.0
2,us-east-1:db841a21-c402-c83f-fadf-41f6d4271053,18.0,14.0,-4.0
4,us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1,16.0,13.0,-3.0
5,us-east-1:db841a21-c403-c5dc-0f8d-fdaad2b0c8c0,14.0,13.0,-1.0
...,...,...,...,...
595,us-east-1:db841a21-c4fe-cc66-e826-c35b57986b93,12.0,20.0,8.0
597,us-east-1:db841a21-c4ff-c868-02a6-5cfff64a075a,8.0,7.0,-1.0
598,us-east-1:db841a21-c4ff-cb45-cad0-4821d631eb58,18.0,21.0,3.0
599,us-east-1:db841a21-c4ff-cb63-a6da-f45b3c81a5c5,5.0,0.0,-5.0
600,us-east-1:db841a21-c4ff-cf28-acdc-a8ab36af1fa3,16.0,6.0,-10.0

In [67]:
import os
import gzip
import json
import pandas as pd

# Define the directory where files are stored
directory = "/path/to/your/local/files"  # Change this to your actual path

# Create a list of file names (1.json.gz to 7.json.gz)
json_gz_files= ['1.json.gz', '2.json.gz', '3.json.gz', '4.json.gz', '5.json.gz', '6.json.gz', '7.json.gz']


dfs = []  # List to store DataFrames

In [68]:


# Loop through each file, extract, and convert to DataFrame
for file_path in json_gz_files:
    with gzip.open(file_path, 'rt', encoding='utf-8') as f:
        records = [json.loads(line) for line in f]  # DynamoDB exports are usually line-separated JSON
    
    # Convert to DataFrame
    df = pd.DataFrame(records)
    dfs.append(df)

# Combine all DataFrames into one
final_df = pd.concat(dfs, ignore_index=True)

# Display DataFrame
print(final_df.head())

# # Optionally, save the combined DataFrame to a CSV file
# final_df.to_csv("combined_data.csv", index=False)

                                                Item
0  {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
1  {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
2  {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
3  {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
4  {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...

In [71]:
final_df.to_csv("location_ascent_combined_data.csv", index=False)

In [73]:
final_df.shape

(9374577, 1)

In [115]:
final_df

                                                      Item
0        {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
1        {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
2        {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
3        {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
4        {'user_id': {'S': 'us-east-1:db841a21-c476-c2c...
...                                                    ...
9374572  {'user_id': {'S': 'us-east-1:db841a21-c436-ccd...
9374573  {'user_id': {'S': 'us-east-1:db841a21-c436-ccd...
9374574  {'user_id': {'S': 'us-east-1:db841a21-c436-ccd...
9374575  {'user_id': {'S': 'us-east-1:db841a21-c436-ccd...
9374576  {'user_id': {'S': 'us-east-1:db841a21-c436-ccd...

[9374577 rows x 1 columns]

In [78]:
final_df.loc[0][0]

/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/4192494348.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  final_df.loc[0][0]

{'user_id': {'S': 'us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920'},
 'timestamp': {'S': '2024-04-26T00:57:19.664000-04:00'},
 'horizontal_accuracy': {'N': '14.6157730208'},
 'event_type': {'S': 'Location'},
 'altitude': {'N': '7.3499999046'},
 'longitude': {'N': '-84.5921590482'},
 'vertical_accuracy': {'N': '8.0423707962'},
 'init_date': {'S': '2024-04-26T00:58:23.357000-04:00'},
 'batch_id': {'S': '1C285CBB-73A8-4484-9542-EF016AA10D64'},
 'creation_timestamp': {'S': '2024-04-26T01:11:32.328000-04:00'},
 'id': {'S': '6d727782-70f1-46bd-ab0f-ee9d512e3a66'},
 'latitude': {'N': '29.8856234373'},
 'duration': {'N': '852.5895229578'},
 'type': {'N': '2'},
 'processing_time': {'S': '2024-06-11T13:38:26.442979+00:00'}}

In [88]:
final_df.loc[0][0]

/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/4192494348.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  final_df.loc[0][0]

{'user_id': {'S': 'us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920'},
 'timestamp': {'S': '2024-04-26T00:57:19.664000-04:00'},
 'horizontal_accuracy': {'N': '14.6157730208'},
 'event_type': {'S': 'Location'},
 'altitude': {'N': '7.3499999046'},
 'longitude': {'N': '-84.5921590482'},
 'vertical_accuracy': {'N': '8.0423707962'},
 'init_date': {'S': '2024-04-26T00:58:23.357000-04:00'},
 'batch_id': {'S': '1C285CBB-73A8-4484-9542-EF016AA10D64'},
 'creation_timestamp': {'S': '2024-04-26T01:11:32.328000-04:00'},
 'id': {'S': '6d727782-70f1-46bd-ab0f-ee9d512e3a66'},
 'latitude': {'N': '29.8856234373'},
 'duration': {'N': '852.5895229578'},
 'type': {'N': '2'},
 'processing_time': {'S': '2024-06-11T13:38:26.442979+00:00'}}

In [80]:
df_sum =pd.read_csv('summary.csv')

/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/385082754.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,61,62,63,65,66,67,68,75,77,79,80,81,82,83,84,85,86,87,89,91,98,99,100,101,102,103,104,105,106,108,109,110,111,113,114,115,116,117,118,119,120,121,122,123,124,125,126,129,130,131,132,133,134,138,139,140,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,188,191,192,193,194,195,196,197,198,199,200,201,202) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sum =pd.read_csv('summary.csv')

In [86]:
len(df_sum)

114739

In [85]:
df_sum.home_lat.value_counts()

home_lat
True             50428
5.356259            64
6.4874673           56
True                51
7.3858606           46
                 ...
39.410517325         1
43.5792665766        1
39.4105442367        1
43.57952455          1
42.7066874737        1
Name: count, Length: 29346, dtype: int64

In [87]:

def pd_read_parquet_from_mlflow(
    #run_id: str, 
    artifact_path: str) -> pd.DataFrame:
    """Load a parquet file from an mlflow artifact.

    Args:
        run_id: the mlflow Run ID
        artifact_path: the relative (to the run) path to the parquet file
    
    Returns:
        pd.DataFrame of the loaded artifact
    """
    #local_path = download_artifacts(run_id=run_id, artifact_path=artifact_path)
    return pd.read_parquet(artifact_path)

#run_id = 'c65b6c792ff240d9a2a415dbca52e4e2'
# path = 'data.parquet'
# df = pd_read_parquet_from_mlflow(path)
# df.head()
path = 'data (1).parquet'
df = pd_read_parquet_from_mlflow(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [91]:
df = df[df.deployment == 'hr-ascent-1']
df.shape

(2924, 158)

In [ ]:
#  Optional: if you have a ts column, sort by user and time
if 'ts' in df.columns:
    df['ts'] = pd.to_datetime(df['ts'])
    df = df.sort_values(by=['user_id', 'ts'])

# Get first and last PHQ8 score for each user
first_scores = df.groupby('user_id').first()['phq8_total']
last_scores = df.groupby('user_id').last()['phq8_total']

# Combine into a new DataFrame
phq_df_1 = pd.DataFrame({
    'phq8_before': first_scores,
    'phq8_after': last_scores
}).reset_index()

# Removing the users who have submitted just once 
counts = df.groupby('user_id')[['phq8_total']].nunique().reset_index()
counts= pd.DataFrame(counts)
counts.columns
counts= counts[counts.phq8_total == 1]
phq_df =  phq_df_1[~phq_df_1['user_id'].isin(counts['user_id'])]

# Compute change
phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']

# Categorize users
no_change = phq_df[phq_df['change'] == 0]
improved = phq_df[phq_df['change'] < 0]
declined = phq_df[phq_df['change'] > 0]

# Summary stats
total = len(phq_df)
no_change_count = len(no_change)
improved_count = len(improved)
declined_count = len(declined)

no_change_percent = round((no_change_count / total) * 100, 1)
improved_percent = round((improved_count / total) * 100, 1)
declined_percent = round((declined_count / total) * 100, 1)

avg_improvement = round(abs(improved['change'].mean()), 2) if improved_count > 0 else 0
avg_decline = round(abs(declined['change'].mean()), 2) if declined_count > 0 else 0

# Output
print(f"{no_change_count}/{total} users had no change ({no_change_percent}%)")
print(f"{improved_count}/{total} users improved ({improved_percent}%) with an average change in PHQ-8 of {avg_improvement} points")
print(f"{declined_count}/{total} users declined ({declined_percent}%) with an average change in PHQ-8 of {avg_decline} points")

In [ ]:
import pandas as pd

# Optional: sort by user and time
if 'ts' in df.columns:
    df['ts'] = pd.to_datetime(df['ts'])
    df = df.sort_values(by=['user_id', 'ts'])

# Get first and last PHQ8 score for each user
first_scores = df.groupby('user_id').first()['phq8_total']
last_scores = df.groupby('user_id').last()['phq8_total']

# Combine into a new DataFrame
phq_df_1 = pd.DataFrame({
    'user_id': first_scores.index,
    'phq8_before': first_scores.values,
    'phq8_after': last_scores.values
})

# Removing users who submitted only once
counts = df.groupby('user_id')[['phq8_total']].nunique().reset_index()
single_entry_users = counts[counts['phq8_total'] == 1]['user_id']
phq_df = phq_df_1[~phq_df_1['user_id'].isin(single_entry_users)]

# Compute change
phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']
phq_df['pct_change'] = (phq_df['change'] / phq_df['phq8_before']) * 100

# Categorize users
no_change = phq_df[phq_df['change'] == 0]
improved = phq_df[phq_df['change'] < 0]
declined = phq_df[phq_df['change'] > 0]

# Summary stats
total = len(phq_df)
no_change_count = len(no_change)
improved_count = len(improved)
declined_count = len(declined)

no_change_percent = round((no_change_count / total) * 100, 1)
improved_percent = round((improved_count / total) * 100, 1)
declined_percent = round((declined_count / total) * 100, 1)

avg_improvement = round(abs(improved['change'].mean()), 2) if improved_count > 0 else 0
avg_decline = round(abs(declined['change'].mean()), 2) if declined_count > 0 else 0

# Output summary
print(f"{no_change_count}/{total} users had no change ({no_change_percent}%)")
print(f"{improved_count}/{total} users improved ({improved_percent}%) with an average change in PHQ-8 of {avg_improvement} points")
print(f"{declined_count}/{total} users declined ({declined_percent}%) with an average change in PHQ-8 of {avg_decline} points")

# === ADDITIONAL CUT ANALYSIS ===

## 1. Users with PHQ8 > 10 – focus on decreases
high_baseline = phq_df[phq_df['phq8_before'] > 10]
high_total = len(high_baseline)
high_decreased = high_baseline[high_baseline['change'] < 0]
high_decreased_pct = round((len(high_decreased) / high_total) * 100, 1) if high_total > 0 else 0
high_avg_pct_decrease = round(abs(high_decreased['pct_change'].mean()), 1) if len(high_decreased) > 0 else 0
high_avg_point_decrease = round(abs(high_decreased['change'].mean()), 2) if len(high_decreased) > 0 else 0

print(f"\nOut of {high_total} users with baseline PHQ-8 >10, {len(high_decreased)} ({high_decreased_pct}%) experienced a decrease.")
print(f"Average percentage decrease among these users: {high_avg_pct_decrease}%")
print(f"Average point decrease: {high_avg_point_decrease} points")


## 2. Users with PHQ8 > 5 – focus on increases
mid_baseline = phq_df[phq_df['phq8_before'] > 5]
mid_total = len(mid_baseline)
mid_increased = mid_baseline[mid_baseline['change'] > 0]
mid_increased_pct = round((len(mid_increased) / mid_total) * 100, 1) if mid_total > 0 else 0
mid_avg_pct_increase = round(mid_increased['pct_change'].mean(), 1) if len(mid_increased) > 0 else 0
mid_avg_point_increase = round(mid_increased['change'].mean(), 2) if len(mid_increased) > 0 else 0

print(f"\nOut of {mid_total} users with baseline PHQ-8 >5, {len(mid_increased)} ({mid_increased_pct}%) experienced an increase.")
print(f"Average percentage increase among these users: {mid_avg_pct_increase}%")
print(f"Average point increase: {mid_avg_point_increase} points")

52/512 users had no change (10.2%)
294/512 users improved (57.4%) with an average change in PHQ-8 of 5.26 points
166/512 users declined (32.4%) with an average change in PHQ-8 of 3.66 points

Out of 379 users with baseline PHQ-8 >10, 237 (62.5%) experienced a decrease.
Average percentage decrease among these users: 34.7%
Average point decrease: 5.63 points

Out of 497 users with baseline PHQ-8 >5, 156 (31.4%) experienced an increase.
Average percentage increase among these users: 33.1%
Average point increase: 3.49 points

/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/2615378759.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']
/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/2615378759.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phq_df['pct_change'] = (phq_df['change'] / phq_df['phq8_before']) * 100

In [97]:

def pd_read_parquet_from_mlflow(
    #run_id: str, 
    artifact_path: str) -> pd.DataFrame:
    """Load a parquet file from an mlflow artifact.

    Args:
        run_id: the mlflow Run ID
        artifact_path: the relative (to the run) path to the parquet file
    
    Returns:
        pd.DataFrame of the loaded artifact
    """
    #local_path = download_artifacts(run_id=run_id, artifact_path=artifact_path)
    return pd.read_parquet(artifact_path)

#run_id = 'c65b6c792ff240d9a2a415dbca52e4e2'
# path = 'data.parquet'
# df = pd_read_parquet_from_mlflow(path)
# df.head()
path = 'data (1).parquet'
df = pd_read_parquet_from_mlflow(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [98]:
df = df[df.deployment == 'hr-ascent-1']
df.shape

(2924, 158)

In [ ]:
import pandas as pd

# Optional: Sort by timestamp
if 'ts' in df.columns:
    df['ts'] = pd.to_datetime(df['ts'])
    df = df.sort_values(by=['user_id', 'ts'])

# Get first and last PHQ score for each user
first_scores = df.groupby('user_id').first()['phq8_total']
last_scores = df.groupby('user_id').last()['phq8_total']

# Combine into new dataframe
phq_df_1 = pd.DataFrame({
    'user_id': first_scores.index,
    'phq8_before': first_scores.values,
    'phq8_after': last_scores.values
})

# Remove users with only one PHQ entry
entry_counts = df.groupby('user_id')['phq8_total'].nunique().reset_index()
single_entry_users = entry_counts[entry_counts['phq8_total'] == 1]['user_id']
phq_df = phq_df_1[~phq_df_1['user_id'].isin(single_entry_users)]

# Calculate change and percent change
phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']
phq_df['pct_change'] = (phq_df['change'] / phq_df['phq8_before']) * 100
print(f"The length of users is: {len(phq_df)}")

### ----------- FUNCTION TO PRINT METRICS FOR ANY SUBGROUP -----------
def analyze_change(sub_df, group_label):
    total_users = len(sub_df)
    if total_users == 0:
        print(f"\n{group_label}: No users in this group.")
        return
    

    # Decreased group
    decreased = sub_df[sub_df['change'] < 0]
    decreased_count = len(decreased)
    decreased_pct = round((decreased_count / total_users) * 100, 1)
    avg_pct_decrease = round(abs(decreased['pct_change'].mean()), 1) if decreased_count > 0 else 0
    avg_point_decrease = round(abs(decreased['change'].mean()), 2) if decreased_count > 0 else 0

    # Increased group
    increased = sub_df[sub_df['change'] > 0]
    increased_count = len(increased)
    increased_pct = round((increased_count / total_users) * 100, 1)
    avg_pct_increase = round(increased['pct_change'].mean(), 1) if increased_count > 0 else 0
    avg_point_increase = round(increased['change'].mean(), 2) if increased_count > 0 else 0
        
    # No change
    nc = sub_df[sub_df['change'] == 0]
    nc_count = len(nc)
    nc_pct = round((nc_count / total_users) * 100, 1)
    avg_pct_nc = round(nc['pct_change'].mean(), 1) if nc_count > 0 else 0
    avg_point_nc = round(nc['change'].mean(), 2) if nc_count > 0 else 0

    # Print Results
    print(f"\n📊 {group_label} (n = {total_users})")
    print(f"- {decreased_count} users ({decreased_pct}%) decreased")
    print(f"   ↪ Avg % decrease: {avg_pct_decrease}%, Avg point decrease: {avg_point_decrease}")

    print(f"- {increased_count} users ({increased_pct}%) increased")
    print(f"   ↪ Avg % increase: {avg_pct_increase}%, Avg point increase: {avg_point_increase}")

    print(f"- {nc_count} users ({nc_pct}%) has no change")
    print(f"   ↪ Avg % of no change users: {avg_pct_nc}%, Avg point of no change users: {avg_point_nc}")

### ----------- ANALYZE BOTH GROUPS -----------

# Group A: Users with baseline PHQ >10
group_a = phq_df[phq_df['phq8_before'] >= 10]
# group_1 = phq_df[phq_df['phq8_before'] < 10]
# group_2 = phq_df[phq_df['phq8_before']  == 10]
# print(f'phq>= 10 {len(group_a)},{len(group_1)},{len(group_2)}, sum = {len(group_a) + len(group_1)}, total df {len(phq_df)}, equals sum = {len(group_a) == len(group_1)}')
analyze_change(group_a, "Users with baseline PHQ8_total >= 10")

# group_c = phq_df[phq_df['phq8_before']< 10]
# analyze_change(group_c, "Users with baseline PHQ8_total < 10")
# Group B: Users with baseline PHQ >5
group_b = phq_df[phq_df['phq8_before'] >= 5]
analyze_change(group_b, "Users with baseline PHQ8_total >= 5")

The length of users is: 512

📊 Users with baseline PHQ8_total >= 10 (n = 408)
- 251 users (61.5%) decreased
   ↪ Avg % decrease: 35.2%, Avg point decrease: 5.56
- 119 users (29.2%) increased
   ↪ Avg % increase: 23.0%, Avg point increase: 3.15
- 38 users (9.3%) has no change
   ↪ Avg % of no change users: 0.0%, Avg point of no change users: 0.0

📊 Users with baseline PHQ8_total >= 5 (n = 504)
- 293 users (58.1%) decreased
   ↪ Avg % decrease: 36.8%, Avg point decrease: 5.27
- 159 users (31.5%) increased
   ↪ Avg % increase: 34.1%, Avg point increase: 3.51
- 52 users (10.3%) has no change
   ↪ Avg % of no change users: 0.0%, Avg point of no change users: 0.0

/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/4248098284.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phq_df['change'] = phq_df['phq8_after'] - phq_df['phq8_before']
/var/folders/j2/xnk4x4h10w7f7rt6gztjqvtm0000gq/T/ipykernel_939/4248098284.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  phq_df['pct_change'] = (phq_df['change'] / phq_df['phq8_before']) * 100

:

In [114]:
phq_df

,user_id,phq8_before,phq8_after,change,pct_change
0,us-east-1:db841a21-c400-c09b-cb33-144516a80231,8.0,7.0,-1.0,-12.500000
1,us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268,17.0,6.0,-11.0,-64.705882
2,us-east-1:db841a21-c402-c83f-fadf-41f6d4271053,18.0,14.0,-4.0,-22.222222
4,us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1,16.0,13.0,-3.0,-18.750000
5,us-east-1:db841a21-c403-c5dc-0f8d-fdaad2b0c8c0,14.0,13.0,-1.0,-7.142857
...,...,...,...,...,...
595,us-east-1:db841a21-c4fe-cc66-e826-c35b57986b93,12.0,20.0,8.0,66.666667
597,us-east-1:db841a21-c4ff-c868-02a6-5cfff64a075a,8.0,7.0,-1.0,-12.500000
598,us-east-1:db841a21-c4ff-cb45-cad0-4821d631eb58,18.0,21.0,3.0,16.666667
599,us-east-1:db841a21-c4ff-cb63-a6da-f45b3c81a5c5,5.0,0.0,-5.0,-100.000000
600,us-east-1:db841a21-c4ff-cf28-acdc-a8ab36af1fa3,16.0,6.0,-10.0,-62.500000

In [1]:
import os
import gzip
import json
import pandas as pd

# Define the directory where files are stored
# directory = "/path/to/your/local/files"  # Change this to your actual path

# # Create a list of file names (1.json.gz to 7.json.gz)
# json_gz_files= ['1.json.gz', '2.json.gz', '3.json.gz', '4.json.gz', '5.json.gz', '6.json.gz', '7.json.gz']


# dfs = []  # List to store DataFrames

folder_path = r'/Users/mobileprogramming/Documents/MPC_CODE/HR_ML_model_building/ascent_location'

# Get the list of all files in the folder
file_list = os.listdir(folder_path)

# Print the names of the files
files = [file_name for file_name in file_list]
files

['1.json.gz',
 '2.json.gz',
 '3.json.gz',
 '6.json.gz',
 '7.json.gz',
 '5.json.gz',
 '4.json.gz']

In [2]:
# Initialize an empty list to store DataFrames
dataframes = []
file_paths = []
# Loop through each file in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.json.gz'):
        file_path = os.path.join(folder_path, file_name)
        file_paths.append(file_path)
        

# Function to flatten the nested structure in the 'Item' column
def flatten_item_column(df):
    # Ensure the 'Item' column is converted to a DataFrame
    if 'Item' in df.columns:
        expanded = pd.json_normalize(df['Item'])  # Flatten the nested JSON in 'Item'
        return pd.concat([df.drop(columns=['Item']), expanded], axis=1)
    return df

# Loop through each file path and process the .json.gz files
for file_path in file_paths:
    try:
        # Read the JSON file into a DataFrame
        df = pd.read_json(file_path, compression='gzip', lines=True)
        
        # Flatten the 'Item' column if it exists
        df = flatten_item_column(df)
        
        dataframes.append(df)
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
# Combine all DataFrames into a single DataFrame
location_df = pd.concat(dataframes, ignore_index=True)

# Display the combined DataFrame
location_df.head()

,user_id.S,timestamp.S,horizontal_accuracy.N,event_type.S,altitude.N,longitude.N,vertical_accuracy.N,init_date.S,batch_id.S,creation_timestamp.S,id.S,latitude.N,duration.N,type.N,processing_time.S,speed.N,course.N,version.N,accuracy.N
0,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,2024-04-26T00:57:19.664000-04:00,14.6157730208,Location,7.3499999046,-84.5921590482,8.0423707962,2024-04-26T00:58:23.357000-04:00,1C285CBB-73A8-4484-9542-EF016AA10D64,2024-04-26T01:11:32.328000-04:00,6d727782-70f1-46bd-ab0f-ee9d512e3a66,29.8856234373,852.5895229578,2,2024-06-11T13:38:26.442979+00:00,NaN,NaN,NaN,NaN
1,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,2024-04-26T01:11:32.253000-04:00,14.6157730208,Location,7.3499999046,-84.5921590482,11.1233024597,2024-04-26T00:58:23.357000-04:00,1C285CBB-73A8-4484-9542-EF016AA10D64,2024-04-26T01:25:53.474000-04:00,e8914834-847f-4af4-a17a-ca6cfc68cedb,29.8856234373,860.9049270153,2,2024-06-11T13:38:26.442979+00:00,NaN,NaN,NaN,NaN
2,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,2024-04-26T01:25:53.158000-04:00,14.6157730208,Location,7.3499999046,-84.5921590482,7.4554538727,2024-04-26T00:58:23.357000-04:00,964621F2-14D2-428D-8990-7378905D266A,2024-04-26T07:39:03.314000-04:00,8fdd16e2-2300-478a-b009-e65f38509e35,29.8856234373,22261.9845750332,2,2024-06-11T13:42:12.033056+00:00,NaN,NaN,NaN,NaN
3,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,2024-04-26T07:36:55.143000-04:00,14.6157730208,Location,8.4941368103,-84.5921590482,15.2944307327,2024-04-26T00:58:23.357000-04:00,964621F2-14D2-428D-8990-7378905D266A,2024-04-26T08:01:46.987000-04:00,3dde0346-b7d1-4022-a6c9-07be52e1681a,29.8856234373,1491.5097159147,2,2024-06-11T13:42:12.033056+00:00,NaN,NaN,NaN,NaN
4,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,2024-04-26T08:01:46.653000-04:00,25.0012903053,Location,9.8933766736,-84.5923599075,1.4546493191,2024-04-26T00:58:23.357000-04:00,ED15EC40-6CF4-4515-8021-CF057093FF24,2024-04-26T08:27:27.367000-04:00,b7bf4fa5-09ca-4692-95b3-c91f39598d3f,29.8855542196,1456.90280509,2,2024-06-11T13:38:39.922645+00:00,0.4396065077,NaN,NaN,NaN

In [4]:
location_df.shape

(9374577, 19)

In [9]:
df_long_lang = location_df[['user_id.S','longitude.N','latitude.N']]#,'longitude.N','latitude.N']
df_long_lang

,user_id.S,longitude.N,latitude.N
0,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,-84.5921590482,29.8856234373
1,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,-84.5921590482,29.8856234373
2,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,-84.5921590482,29.8856234373
3,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,-84.5921590482,29.8856234373
4,us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920,-84.5923599075,29.8855542196
...,...,...,...
9374572,us-east-1:db841a21-c4d5-c76c-b22b-0656fb5a9789,3.8602811,7.4762785
9374573,us-east-1:db841a21-c4d5-c76c-b22b-0656fb5a9789,3.8510567,7.4736584
9374574,us-east-1:db841a21-c4d5-c76c-b22b-0656fb5a9789,3.8602811,7.4762785
9374575,us-east-1:db841a21-c4d5-c76c-b22b-0656fb5a9789,3.8602811,7.4762785
9374576,us-east-1:db841a21-c4d5-c76c-b22b-0656fb5a9789,3.8602811,7.4762785

In [10]:
df_long_lang['latitude.N'].value_counts()

latitude.N
40.8803247       31559
32.7834017        7295
5.1334622         4384
39.0437567        4333
32.7821334        2858
                 ...
39.3104078313        1
39.3160213538        1
39.3122084849        1
39.2878543327        1
37.2384986           1
Name: count, Length: 2413263, dtype: int64

In [12]:
df_long_lang['latitude.N'].isna().value_counts()

latitude.N
False    9374577
Name: count, dtype: int64

In [13]:
df_long_lang['longitude.N'].isna().value_counts()

longitude.N
False    9374577
Name: count, dtype: int64