In [20]:
import os
import tempfile

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go


import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.distributions.empirical_distribution import ECDF

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer

import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter(action='ignore', category=FutureWarning)

In [21]:
def pd_read_parquet(artifact_path: str) -> pd.DataFrame:
    '''
    This function should read a Parquet file located at the provided path and return a pandas DataFrame.
    '''
    return pd.read_parquet(artifact_path)

path = 'data (1).parquet'
df = pd_read_parquet(path)
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:1b087523-b47b-421c-97c4-74da80564598,2018-09-25 18:17:26.647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,0.0,1.0,1.0,1.0,NaN,3.0,9.0,NaN,hr-rct-cue-1
1,us-east-1:ea986d8e-e87d-458b-a798-1999fbbff05b,2018-09-26 17:13:52.394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,NaN,4.0,21.0,NaN,hr-rct-cue-1
2,us-east-1:8dfca9b6-22b6-4155-8a70-ce3e1211a684,2018-09-27 19:04:15.124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,1.0,NaN,6.0,22.0,NaN,hr-rct-cue-1
3,us-east-1:77f43bb4-fe8e-4a50-a4fc-41bc14b11f9d,2018-10-01 22:01:32.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,2.0,2.0,0.0,NaN,2.0,10.0,NaN,hr-rct-cue-1
4,us-east-1:4940dfa3-1c01-49f2-9cdd-029291d7b7a8,2018-10-05 21:08:52.441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,3.0,3.0,1.0,0.0,NaN,6.0,18.0,NaN,hr-rct-cue-1

In [22]:
#print the shape of the dataset.
print(df.shape)
print('Count of rows:', df.shape[0])
print('Count of columns:', df.shape[1])

(6820, 158)
Count of rows: 6820
Count of columns: 158

In [23]:
# For stakeholders: Filter the dataset to include only the 'hr-ascent-1' deployment
df = df[df.deployment == 'hr-ascent-1']
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq_q4,phq_q5,phq_q6,phq_q7,phq_q8,phq_q9,phq2_total,phq8_total,phq9_total,deployment
0,us-east-1:db841a21-c4fd-cf09-4379-5af0b6185e0e,2024-03-23 21:58:52.242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,2.0,3.0,3.0,1.0,6.0,23.0,24.0,hr-ascent-1
1,us-east-1:db841a21-c48b-cd1c-563f-eb23aa6c2768,2024-03-26 14:46:43.386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,1.0,2.0,2.0,1.0,5.0,19.0,20.0,hr-ascent-1
2,us-east-1:db841a21-c46a-c6fd-ca13-1faabac2c46d,2024-03-27 16:19:40.526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,1.0,1.0,1.0,1.0,0.0,4.0,12.0,12.0,hr-ascent-1
3,us-east-1:db841a21-c4b2-c6b9-91ed-370b2da2aa86,2024-03-27 16:42:15.485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,2.0,3.0,1.0,1.0,6.0,21.0,22.0,hr-ascent-1
4,us-east-1:db841a21-c438-c76a-5078-c47a75e6b0c3,2024-03-28 14:52:36.017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,0.0,2.0,7.0,7.0,hr-ascent-1

In [24]:
#print the shape of the dataset.
print(df.shape)
print('Count of rows:', df.shape[0])
print('Count of columns:', df.shape[1])

(2924, 158)
Count of rows: 2924
Count of columns: 158

### The PHQ-9 is a depression screening tool with nine questions:

1. Anhedonia (loss of interest)

2. Depressed mood

3. Sleep issues

4. Fatigue

5. Appetite changes

6. Guilt/worthlessness

7. Concentration issues

8. Psychomotor agitation/retardation

9. Suicidal thoughts

### The original mappings were:

- Sleep: PHQ-1, PHQ-3, PHQ-4

- Activity: PHQ-1, PHQ-4, PHQ-7

- Sociability: PHQ-1, PHQ-6, PHQ-9

- Device Usage: PHQ-2, PHQ-5, PHQ-8


### 1. Sleep Features
Key Insight: Sleep disruptions directly impact circadian rhythms and trickle down to activity/sociability.
    
    PHQ-3 ("Trouble sleeping") is the direct correlate for sleep disruptions.
    PHQ-4 ("Feeling tired/low energy") reflects the downstream effect of poor sleep.

    PHQ-9 Mapping: Primary: PHQ-3 (core sleep disturbance), Secondary: PHQ-4 (fatigue from poor sleep)


##### Features
    sleep_duration_m7, sleep_duration_m14, sleep_duration_s7, sleep_duration_s14
    sleep_start_m7, sleep_start_m14, sleep_start_s7, sleep_start_s14
    sleep_end_m7, sleep_end_m14, sleep_end_s7, sleep_end_s14
    sleep_interruptions_m7, sleep_interruptions_m14, sleep_interruptions_s7, sleep_interruptions_s14
    sleep_routine_index_m7, sleep_routine_index_m14, sleep_routine_index_s7, sleep_routine_index_s14
    chronotype_score_m7, chronotype_score_m14, chronotype_score_s7, chronotype_score_s14

### 2. Activity Features
Key Insight: Physical activity correlates with energy levels and mental engagement.

    PHQ-1 ("Little interest/pleasure") aligns with reduced physical engagement.
    PHQ-4 ("Low energy") correlates with activity levels.

    PHQ-9 Mapping: PHQ-1 (Loss of interest), PHQ-4 (Fatigue).

##### Features
    active_time_m7, active_time_m14, active_time_s7, active_time_s14
    activity_percent_m7, activity_percent_m14, activity_percent_s7, activity_percent_s14
    ec_Activity_m7, ec_Activity_m14, ec_Activity_s7, ec_Activity_s14
    ec_PedometerData_m7, ec_PedometerData_m14, ec_PedometerData_s7, ec_PedometerData_s14
    step_count_m7, step_count_m14, step_count_s7, step_count_s14
    steps_most_active_10h_m7, steps_most_active_10h_m14, steps_most_active_10h_s7, steps_most_active_10h_s14
    steps_least_active_5h_m7, steps_least_active_5h_m14, steps_least_active_5h_s7, steps_least_active_5h_s14
    steps_relative_amplitude_m7, steps_relative_amplitude_m14, steps_relative_amplitude_s7, steps_relative_amplitude_s14
    walking_rate_m7, walking_rate_m14, walking_rate_s7, walking_rate_s14
    total_activity_duration_m7, total_activity_duration_m14, total_activity_duration_s7, total_activity_duration_s14

### 3. Sociability Features
Key Insight: Movement outside home and location diversity reflect social engagement.

    PHQ-1 ("Withdrawal from social activities") strongly aligns with location entropy/clusters.
    PHQ-6 ("Feeling worthless") may correlate with isolation (time at home).


    PHQ-9 Mapping: PHQ-1 (social withdrawal), PHQ-6 (isolation → guilt).

##### Features
    time_at_home_m7, time_at_home_m14, time_at_home_s7, time_at_home_s14
    time_at_location_1_m7, time_at_location_1_m14, ..., time_at_location_5_s14
    num_location_clusters_m7, num_location_clusters_m14, num_location_clusters_s7, num_location_clusters_s14
    loc_entropy_m7, loc_entropy_m14, loc_entropy_s7, loc_entropy_s14
    travel_diameter_m7, travel_diameter_m14, travel_diameter_s7, travel_diameter_s14
    ec_Location_m7, ec_Location_m14, ec_Location_s7, ec_Location_s14
    total_location_duration_m7, total_location_duration_m14, total_location_duration_s7, total_location_duration_s14

### 4. Device Usage Features (New Bucket)
Key Insight: Screen time may reflect avoidance behaviors or reduced physical/social activity.
    PHQ-2 ("Feeling down") correlates with increased passive screen time.
    PHQ-8 ("Fidgeting/slowing") maps to screen unlocks (agitation) or low usage (retardation).

    PHQ-9 Mapping: PHQ-2 (Mood), PHQ-8 (Psychomotor agitation).

##### Features
    ec_DeviceDisplayStatus_m7, ec_DeviceDisplayStatus_m14, ec_DeviceDisplayStatus_s7, ec_DeviceDisplayStatus_s14
    display_events_m7, display_events_m14, display_events_s7, display_events_s14
    screen_unlocks_m7, screen_unlocks_m14, screen_unlocks_s7, screen_unlocks_s14
    total_display_duration_m7, total_display_duration_m14, total_display_duration_s7, total_display_duration_s14
    device_use_percent_m7, device_use_percent_m14, device_use_percent_s7, device_use_percent_s14

### 5. Demographic Features
Key Insight: Age, occupation, and ethnicity may moderate mental health outcomes.

##### Features
    age_bucket, age_num, sex, gender, housemates, occupation, school, phone_carry, full_time, ethnicity, ethnicity_white, age_binary, chronotype

### 6. Other/General Features
Purpose: Metadata or composite metrics.

##### Features
    user_id, ts, ec_total_m7, ec_total_m14, ec_total_s7, ec_total_s14, deployment

### Notes on Weighting for BVC
    Sleep likely has the highest weight due to its trickle-down effect on activity/sociability.
    Activity and Sociability weights can be derived from regression coefficients in the model.
    Device Usage may act as a confounder (e.g., high screen time → low activity).

In [46]:
def categorize_features():
    # Feature Bucket Definitions
    buckets = {
        "Sleep": [
            # Sleep duration/patterns
            'sleep_duration_m7', 'sleep_duration_m14', 'sleep_duration_s7', 'sleep_duration_s14',
            'sleep_start_m7', 'sleep_start_m14', 'sleep_start_s7', 'sleep_start_s14',
            'sleep_end_m7', 'sleep_end_m14', 'sleep_end_s7', 'sleep_end_s14',
            'sleep_interruptions_m7', 'sleep_interruptions_m14', 'sleep_interruptions_s7', 'sleep_interruptions_s14',
            
            # Sleep quality metrics
            'sleep_routine_index_m7', 'sleep_routine_index_m14', 'sleep_routine_index_s7', 'sleep_routine_index_s14',
            'chronotype_score_m7', 'chronotype_score_m14', 'chronotype_score_s7', 'chronotype_score_s14'
        ],
        
        "Activity": [
            # Physical activity metrics
            'active_time_m7', 'active_time_m14', 'active_time_s7', 'active_time_s14',
            'activity_percent_m7', 'activity_percent_m14', 'activity_percent_s7', 'activity_percent_s14',
            'ec_Activity_m7', 'ec_Activity_m14', 'ec_Activity_s7', 'ec_Activity_s14',
            'ec_PedometerData_m7', 'ec_PedometerData_m14', 'ec_PedometerData_s7', 'ec_PedometerData_s14',
            
            # Step-based metrics
            'step_count_m7', 'step_count_m14', 'step_count_s7', 'step_count_s14',
            'steps_most_active_10h_m7', 'steps_most_active_10h_m14', 'steps_most_active_10h_s7', 'steps_most_active_10h_s14',
            'steps_least_active_5h_m7', 'steps_least_active_5h_m14', 'steps_least_active_5h_s7', 'steps_least_active_5h_s14',
            'steps_relative_amplitude_m7', 'steps_relative_amplitude_m14', 'steps_relative_amplitude_s7', 'steps_relative_amplitude_s14',
            
            # Movement metrics
            'walking_rate_m7', 'walking_rate_m14', 'walking_rate_s7', 'walking_rate_s14',
            'total_activity_duration_m7', 'total_activity_duration_m14', 'total_activity_duration_s7', 'total_activity_duration_s14'
        ],
        
        "Sociability": [
            # Location patterns
            'time_at_home_m7', 'time_at_home_m14', 'time_at_home_s7', 'time_at_home_s14',
            
            # Location clusters (all variations)
            *[f'time_at_location_{i}_m7' for i in range(1,6)],
            *[f'time_at_location_{i}_m14' for i in range(1,6)],
            *[f'time_at_location_{i}_s7' for i in range(1,6)],
            *[f'time_at_location_{i}_s14' for i in range(1,6)],
            
            # Location diversity metrics
            'num_location_clusters_m7', 'num_location_clusters_m14', 'num_location_clusters_s7', 'num_location_clusters_s14',
            'loc_entropy_m7', 'loc_entropy_m14', 'loc_entropy_s7', 'loc_entropy_s14',
            'travel_diameter_m7', 'travel_diameter_m14', 'travel_diameter_s7', 'travel_diameter_s14',
            
            # Location event metrics
            'ec_Location_m7', 'ec_Location_m14', 'ec_Location_s7', 'ec_Location_s14',
            'total_location_duration_m7', 'total_location_duration_m14', 'total_location_duration_s7', 'total_location_duration_s14'
        ],
        
        "Device Usage": [
            # Screen interaction metrics
            'ec_DeviceDisplayStatus_m7', 'ec_DeviceDisplayStatus_m14', 'ec_DeviceDisplayStatus_s7', 'ec_DeviceDisplayStatus_s14',
            'display_events_m7', 'display_events_m14', 'display_events_s7', 'display_events_s14',
            'screen_unlocks_m7', 'screen_unlocks_m14', 'screen_unlocks_s7', 'screen_unlocks_s14',
            
            # Device usage patterns
            'total_display_duration_m7', 'total_display_duration_m14', 'total_display_duration_s7', 'total_display_duration_s14',
            'device_use_percent_m7', 'device_use_percent_m14', 'device_use_percent_s7', 'device_use_percent_s14'
        ],
        
        "Demographic": [
            # User profile data
            'age_bucket', 'age_num', 'sex', 'gender', 'housemates', 'occupation', 
            'school', 'phone_carry', 'full_time', 'ethnicity', 'ethnicity_white', 
            'age_binary', 'chronotype'
        ],
        
        "Other": [
            # Technical/metadata fields
            'user_id', 'ts', 'deployment',
            
            # Composite event counts
            'ec_total_m7', 'ec_total_m14', 'ec_total_s7', 'ec_total_s14'
        ],
        
        "Target": [
            # PHQ-9 questionnaire items
            'phq_q1', 'phq_q2', 'phq_q3', 'phq_q4', 'phq_q5', 
            'phq_q6', 'phq_q7', 'phq_q8', 'phq_q9',
            
            # PHQ scores and categories
            'phq2_total', 'phq8_total', 'phq9_total', 'phq_category'
        ]
    }

    # Validation check to ensure all features are categorized
    all_features = sum(buckets.values(), [])
    original_features = df.columns

    # Check for uncategorized features
    uncategorized = [f for f in original_features if f not in all_features]
    if uncategorized:
        print("Warning: Uncategorized features detected:", uncategorized)
        buckets["Uncategorized"] = uncategorized

    return buckets

# Usage Example:
feature_buckets = categorize_features()

# Print bucket sizes
for category, features in feature_buckets.items():
    print(f"{category}: {len(features)} features")

# To get features for a specific bucket:
sleep_features = feature_buckets["Sleep"]
activity_features = feature_buckets["Activity"]
target_features = feature_buckets["Target"]

Sleep: 24 features
Activity: 40 features
Sociability: 44 features
Device Usage: 20 features
Demographic: 13 features
Other: 7 features
Target: 13 features

In [47]:
feature_buckets

{'Sleep': ['sleep_duration_m7',
  'sleep_duration_m14',
  'sleep_duration_s7',
  'sleep_duration_s14',
  'sleep_start_m7',
  'sleep_start_m14',
  'sleep_start_s7',
  'sleep_start_s14',
  'sleep_end_m7',
  'sleep_end_m14',
  'sleep_end_s7',
  'sleep_end_s14',
  'sleep_interruptions_m7',
  'sleep_interruptions_m14',
  'sleep_interruptions_s7',
  'sleep_interruptions_s14',
  'sleep_routine_index_m7',
  'sleep_routine_index_m14',
  'sleep_routine_index_s7',
  'sleep_routine_index_s14',
  'chronotype_score_m7',
  'chronotype_score_m14',
  'chronotype_score_s7',
  'chronotype_score_s14'],
 'Activity': ['active_time_m7',
  'active_time_m14',
  'active_time_s7',
  'active_time_s14',
  'activity_percent_m7',
  'activity_percent_m14',
  'activity_percent_s7',
  'activity_percent_s14',
  'ec_Activity_m7',
  'ec_Activity_m14',
  'ec_Activity_s7',
  'ec_Activity_s14',
  'ec_PedometerData_m7',
  'ec_PedometerData_m14',
  'ec_PedometerData_s7',
  'ec_PedometerData_s14',
  'step_count_m7',
  'step_count_m14',
  'step_count_s7',
  'step_count_s14',
  'steps_most_active_10h_m7',
  'steps_most_active_10h_m14',
  'steps_most_active_10h_s7',
  'steps_most_active_10h_s14',
  'steps_least_active_5h_m7',
  'steps_least_active_5h_m14',
  'steps_least_active_5h_s7',
  'steps_least_active_5h_s14',
  'steps_relative_amplitude_m7',
  'steps_relative_amplitude_m14',
  'steps_relative_amplitude_s7',
  'steps_relative_amplitude_s14',
  'walking_rate_m7',
  'walking_rate_m14',
  'walking_rate_s7',
  'walking_rate_s14',
  'total_activity_duration_m7',
  'total_activity_duration_m14',
  'total_activity_duration_s7',
  'total_activity_duration_s14'],
 'Sociability': ['time_at_home_m7',
  'time_at_home_m14',
  'time_at_home_s7',
  'time_at_home_s14',
  'time_at_location_1_m7',
  'time_at_location_2_m7',
  'time_at_location_3_m7',
  'time_at_location_4_m7',
  'time_at_location_5_m7',
  'time_at_location_1_m14',
  'time_at_location_2_m14',
  'time_at_location_3_m14',
  'time_at_location_4_m14',
  'time_at_location_5_m14',
  'time_at_location_1_s7',
  'time_at_location_2_s7',
  'time_at_location_3_s7',
  'time_at_location_4_s7',
  'time_at_location_5_s7',
  'time_at_location_1_s14',
  'time_at_location_2_s14',
  'time_at_location_3_s14',
  'time_at_location_4_s14',
  'time_at_location_5_s14',
  'num_location_clusters_m7',
  'num_location_clusters_m14',
  'num_location_clusters_s7',
  'num_location_clusters_s14',
  'loc_entropy_m7',
  'loc_entropy_m14',
  'loc_entropy_s7',
  'loc_entropy_s14',
  'travel_diameter_m7',
  'travel_diameter_m14',
  'travel_diameter_s7',
  'travel_diameter_s14',
  'ec_Location_m7',
  'ec_Location_m14',
  'ec_Location_s7',
  'ec_Location_s14',
  'total_location_duration_m7',
  'total_location_duration_m14',
  'total_location_duration_s7',
  'total_location_duration_s14'],
 'Device Usage': ['ec_DeviceDisplayStatus_m7',
  'ec_DeviceDisplayStatus_m14',
  'ec_DeviceDisplayStatus_s7',
  'ec_DeviceDisplayStatus_s14',
  'display_events_m7',
  'display_events_m14',
  'display_events_s7',
  'display_events_s14',
  'screen_unlocks_m7',
  'screen_unlocks_m14',
  'screen_unlocks_s7',
  'screen_unlocks_s14',
  'total_display_duration_m7',
  'total_display_duration_m14',
  'total_display_duration_s7',
  'total_display_duration_s14',
  'device_use_percent_m7',
  'device_use_percent_m14',
  'device_use_percent_s7',
  'device_use_percent_s14'],
 'Demographic': ['age_bucket',
  'age_num',
  'sex',
  'gender',
  'housemates',
  'occupation',
  'school',
  'phone_carry',
  'full_time',
  'ethnicity',
  'ethnicity_white',
  'age_binary',
  'chronotype'],
 'Other': ['user_id',
  'ts',
  'deployment',
  'ec_total_m7',
  'ec_total_m14',
  'ec_total_s7',
  'ec_total_s14'],
 'Target': ['phq_q1',
  'phq_q2',
  'phq_q3',
  'phq_q4',
  'phq_q5',
  'phq_q6',
  'phq_q7',
  'phq_q8',
  'phq_q9',
  'phq2_total',
  'phq8_total',
  'phq9_total',
  'phq_category']}

In [43]:
sleep_features

['sleep_duration_m7',
 'sleep_duration_m14',
 'sleep_duration_s7',
 'sleep_duration_s14',
 'sleep_start_m7',
 'sleep_start_m14',
 'sleep_start_s7',
 'sleep_start_s14',
 'sleep_end_m7',
 'sleep_end_m14',
 'sleep_end_s7',
 'sleep_end_s14',
 'sleep_interruptions_m7',
 'sleep_interruptions_m14',
 'sleep_interruptions_s7',
 'sleep_interruptions_s14',
 'sleep_routine_index_m7',
 'sleep_routine_index_m14',
 'sleep_routine_index_s7',
 'sleep_routine_index_s14',
 'chronotype_score_m7',
 'chronotype_score_m14',
 'chronotype_score_s7',
 'chronotype_score_s14']

In [26]:
24+40+44+20
# +13+7+13

128

In [27]:
feature_buckets

{'Sleep': ['sleep_duration_m7',
  'sleep_duration_m14',
  'sleep_duration_s7',
  'sleep_duration_s14',
  'sleep_start_m7',
  'sleep_start_m14',
  'sleep_start_s7',
  'sleep_start_s14',
  'sleep_end_m7',
  'sleep_end_m14',
  'sleep_end_s7',
  'sleep_end_s14',
  'sleep_interruptions_m7',
  'sleep_interruptions_m14',
  'sleep_interruptions_s7',
  'sleep_interruptions_s14',
  'sleep_routine_index_m7',
  'sleep_routine_index_m14',
  'sleep_routine_index_s7',
  'sleep_routine_index_s14',
  'chronotype_score_m7',
  'chronotype_score_m14',
  'chronotype_score_s7',
  'chronotype_score_s14'],
 'Activity': ['active_time_m7',
  'active_time_m14',
  'active_time_s7',
  'active_time_s14',
  'activity_percent_m7',
  'activity_percent_m14',
  'activity_percent_s7',
  'activity_percent_s14',
  'ec_Activity_m7',
  'ec_Activity_m14',
  'ec_Activity_s7',
  'ec_Activity_s14',
  'ec_PedometerData_m7',
  'ec_PedometerData_m14',
  'ec_PedometerData_s7',
  'ec_PedometerData_s14',
  'step_count_m7',
  'step_count_m14',
  'step_count_s7',
  'step_count_s14',
  'steps_most_active_10h_m7',
  'steps_most_active_10h_m14',
  'steps_most_active_10h_s7',
  'steps_most_active_10h_s14',
  'steps_least_active_5h_m7',
  'steps_least_active_5h_m14',
  'steps_least_active_5h_s7',
  'steps_least_active_5h_s14',
  'steps_relative_amplitude_m7',
  'steps_relative_amplitude_m14',
  'steps_relative_amplitude_s7',
  'steps_relative_amplitude_s14',
  'walking_rate_m7',
  'walking_rate_m14',
  'walking_rate_s7',
  'walking_rate_s14',
  'total_activity_duration_m7',
  'total_activity_duration_m14',
  'total_activity_duration_s7',
  'total_activity_duration_s14'],
 'Sociability': ['time_at_home_m7',
  'time_at_home_m14',
  'time_at_home_s7',
  'time_at_home_s14',
  'time_at_location_1_m7',
  'time_at_location_2_m7',
  'time_at_location_3_m7',
  'time_at_location_4_m7',
  'time_at_location_5_m7',
  'time_at_location_1_m14',
  'time_at_location_2_m14',
  'time_at_location_3_m14',
  'time_at_location_4_m14',
  'time_at_location_5_m14',
  'time_at_location_1_s7',
  'time_at_location_2_s7',
  'time_at_location_3_s7',
  'time_at_location_4_s7',
  'time_at_location_5_s7',
  'time_at_location_1_s14',
  'time_at_location_2_s14',
  'time_at_location_3_s14',
  'time_at_location_4_s14',
  'time_at_location_5_s14',
  'num_location_clusters_m7',
  'num_location_clusters_m14',
  'num_location_clusters_s7',
  'num_location_clusters_s14',
  'loc_entropy_m7',
  'loc_entropy_m14',
  'loc_entropy_s7',
  'loc_entropy_s14',
  'travel_diameter_m7',
  'travel_diameter_m14',
  'travel_diameter_s7',
  'travel_diameter_s14',
  'ec_Location_m7',
  'ec_Location_m14',
  'ec_Location_s7',
  'ec_Location_s14',
  'total_location_duration_m7',
  'total_location_duration_m14',
  'total_location_duration_s7',
  'total_location_duration_s14'],
 'Device Usage': ['ec_DeviceDisplayStatus_m7',
  'ec_DeviceDisplayStatus_m14',
  'ec_DeviceDisplayStatus_s7',
  'ec_DeviceDisplayStatus_s14',
  'display_events_m7',
  'display_events_m14',
  'display_events_s7',
  'display_events_s14',
  'screen_unlocks_m7',
  'screen_unlocks_m14',
  'screen_unlocks_s7',
  'screen_unlocks_s14',
  'total_display_duration_m7',
  'total_display_duration_m14',
  'total_display_duration_s7',
  'total_display_duration_s14',
  'device_use_percent_m7',
  'device_use_percent_m14',
  'device_use_percent_s7',
  'device_use_percent_s14'],
 'Demographic': ['age_bucket',
  'age_num',
  'sex',
  'gender',
  'housemates',
  'occupation',
  'school',
  'phone_carry',
  'full_time',
  'ethnicity',
  'ethnicity_white',
  'age_binary',
  'chronotype'],
 'Other': ['user_id',
  'ts',
  'deployment',
  'ec_total_m7',
  'ec_total_m14',
  'ec_total_s7',
  'ec_total_s14'],
 'Target': ['phq_q1',
  'phq_q2',
  'phq_q3',
  'phq_q4',
  'phq_q5',
  'phq_q6',
  'phq_q7',
  'phq_q8',
  'phq_q9',
  'phq2_total',
  'phq8_total',
  'phq9_total',
  'phq_category']}

In [28]:


def scale_feature_buckets(df, feature_buckets):
    """
    Performs bucketed scaling while handling missing values and preserving non-scaled columns
    """
    # Create a copy of the dataframe to preserve original data
    scaled_df = df.copy()
    
    # Buckets to scale (excluding Demographic, Other, and Target)
    buckets_to_scale = ['Sleep', 'Activity', 'Sociability', 'Device Usage']
    
    # Create a combined list of all columns to exclude from scaling
    exclude_columns = sum([feature_buckets[b] for b in ['Demographic', 'Other', 'Target']], [])
    
    for bucket in buckets_to_scale:
        bucket_features = [f for f in feature_buckets[bucket] if f in scaled_df.columns]
        
        if not bucket_features:
            continue
            
        # Step 1: Handle missing values using mean imputation
        # imputer = SimpleImputer(strategy='mean')
        # scaled_df[bucket_features] = imputer.fit_transform(scaled_df[bucket_features])
        
        # Step 2: Perform Standard Scaling
        scaler = StandardScaler(with_mean=False, with_std=True)
        scaled_data = scaler.fit_transform(scaled_df[bucket_features])
        
        # Convert back to DataFrame to preserve column names
        scaled_df[bucket_features] = pd.DataFrame(scaled_data, 
                                                columns=bucket_features,
                                                index=scaled_df.index)
        
    # Preserve non-scaled columns (original values where not scaled)
    for col in exclude_columns:
        if col in scaled_df.columns:
            scaled_df[col] = df[col]  # Keep original values
    
    return scaled_df

# Usage Example:
feature_buckets = categorize_features()  # From previous implementation
scaled_df = scale_feature_buckets(df, feature_buckets)

In [29]:
import os
import pandas as pd
import statsmodels.formula.api as smf
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

def process_and_analyze_buckets(df, feature_buckets, target='phq8_total'):
    """Main function to process buckets and run analyses"""
    # Create age binary column
    def get_binary_age(age_bucket: str):
        if pd.isnull(age_bucket):
            return None
        if '85' in str(age_bucket):
            return 'old'
        try:
            ub = int(str(age_bucket).strip().split('-')[-1])
            return 'young' if ub < 45 else 'old'
        except:
            return None
    
    df['age_binary'] = df.age_bucket.apply(get_binary_age)
    
    # Define buckets to process
    buckets_to_process = ['Sleep', 'Activity', 'Sociability', 'Device Usage']
    
    # Create base output directory
    output_dir = os.path.join(os.getcwd(), "regression_results")
    os.makedirs(output_dir, exist_ok=True)
    
    # Process each bucket
    for bucket in buckets_to_process:
        print(f"\nProcessing {bucket} bucket...")
        bucket_features = [f for f in feature_buckets[bucket] if f in df.columns]
        
        # Skip if no features found
        if not bucket_features:
            print(f"No features found for {bucket} bucket")
            continue
            
        # Create bucket-specific directory
        bucket_dir = os.path.join(output_dir, bucket.lower().replace(" ", "_"))
        os.makedirs(bucket_dir, exist_ok=True)
        
        # Process each feature in the bucket
        for feature in bucket_features:
            try:
                # Prepare temporary dataframe
                temp_df = df[['user_id', target, 'sex', 'age_bucket', 'age_binary'] + [feature]].copy()
                
                # Handle missing values and filtering
                temp_df = temp_df.dropna(subset=[feature, target, 'sex', 'age_binary'])
                temp_df = temp_df[temp_df.sex != 'Other']
                
                # Check if data remains
                if temp_df.empty:
                    print(f"Skipping {feature} - no data after cleaning")
                    continue
                    
                # Scale the feature
                scaler = StandardScaler(with_mean=False, with_std=True)
                # imputer = SimpleImputer(strategy='mean')
                
                # Impute and scale
                # temp_df[feature] = imputer.fit_transform(temp_df[[feature]])
                temp_df[feature] = scaler.fit_transform(temp_df[[feature]])
                
                # Ensure proper data types
                temp_df['sex'] = temp_df.sex.astype('category')
                temp_df['age_binary'] = temp_df.age_binary.astype('category')
                
                # Build model formula
                formula = f"{target} ~ Q('{feature}') : C(sex) : C(age_binary)"
                
                # Fit model
                model = smf.ols(formula, data=temp_df).fit()
                
                # Save results
                log_file = os.path.join(bucket_dir, f"{feature}.txt")
                with open(log_file, 'w') as f:
                    f.write(str(model.summary()))
                    
                print(f"Processed {feature} in {bucket}")
                
            except Exception as e:
                print(f"Failed processing {feature}: {str(e)}")
                continue

# Get feature buckets from previous implementation
feature_buckets = categorize_features()

# Run the analysis pipeline
process_and_analyze_buckets(
    df=df,
    feature_buckets=feature_buckets,
    target='phq8_total'  # Can change to other targets if needed
)

Processing Sleep bucket...
Processed sleep_duration_m7 in Sleep
Processed sleep_duration_m14 in Sleep
Processed sleep_duration_s7 in Sleep
Processed sleep_duration_s14 in Sleep
Processed sleep_start_m7 in Sleep
Processed sleep_start_m14 in Sleep
Processed sleep_start_s7 in Sleep
Processed sleep_start_s14 in Sleep
Processed sleep_end_m7 in Sleep
Processed sleep_end_m14 in Sleep
Processed sleep_end_s7 in Sleep
Processed sleep_end_s14 in Sleep
Processed sleep_interruptions_m7 in Sleep
Processed sleep_interruptions_m14 in Sleep
Processed sleep_interruptions_s7 in Sleep
Processed sleep_interruptions_s14 in Sleep
Processed sleep_routine_index_m7 in Sleep
Processed sleep_routine_index_m14 in Sleep
Processed sleep_routine_index_s7 in Sleep
Processed sleep_routine_index_s14 in Sleep
Processed chronotype_score_m7 in Sleep
Processed chronotype_score_m14 in Sleep
Processed chronotype_score_s7 in Sleep
Processed chronotype_score_s14 in Sleep

Processing Activity bucket...
Processed active_time_m7 in Activity
Processed active_time_m14 in Activity
Processed active_time_s7 in Activity
Processed active_time_s14 in Activity
Processed activity_percent_m7 in Activity
Processed activity_percent_m14 in Activity
Processed activity_percent_s7 in Activity
Processed activity_percent_s14 in Activity
Processed ec_Activity_m7 in Activity
Processed ec_Activity_m14 in Activity
Processed ec_Activity_s7 in Activity
Processed ec_Activity_s14 in Activity
Processed ec_PedometerData_m7 in Activity
Processed ec_PedometerData_m14 in Activity
Processed ec_PedometerData_s7 in Activity
Processed ec_PedometerData_s14 in Activity
Processed step_count_m7 in Activity
Processed step_count_m14 in Activity
Processed step_count_s7 in Activity
Processed step_count_s14 in Activity
Processed steps_most_active_10h_m7 in Activity
Processed steps_most_active_10h_m14 in Activity
Processed steps_most_active_10h_s7 in Activity
Processed steps_most_active_10h_s14 in Activity
Processed steps_least_active_5h_m7 in Activity
Processed steps_least_active_5h_m14 in Activity
Processed steps_least_active_5h_s7 in Activity
Processed steps_least_active_5h_s14 in Activity
Processed steps_relative_amplitude_m7 in Activity
Processed steps_relative_amplitude_m14 in Activity
Processed steps_relative_amplitude_s7 in Activity
Processed steps_relative_amplitude_s14 in Activity
Processed walking_rate_m7 in Activity
Processed walking_rate_m14 in Activity
Processed walking_rate_s7 in Activity
Processed walking_rate_s14 in Activity
Processed total_activity_duration_m7 in Activity
Processed total_activity_duration_m14 in Activity
Processed total_activity_duration_s7 in Activity
Processed total_activity_duration_s14 in Activity

Processing Sociability bucket...
Processed time_at_home_m7 in Sociability
Processed time_at_home_m14 in Sociability
Processed time_at_home_s7 in Sociability
Processed time_at_home_s14 in Sociability
Processed time_at_location_1_m7 in Sociability
Processed time_at_location_2_m7 in Sociability
Processed time_at_location_3_m7 in Sociability
Processed time_at_location_4_m7 in Sociability
Processed time_at_location_5_m7 in Sociability
Processed time_at_location_1_m14 in Sociability
Processed time_at_location_2_m14 in Sociability
Processed time_at_location_3_m14 in Sociability
Processed time_at_location_4_m14 in Sociability
Processed time_at_location_5_m14 in Sociability
Processed time_at_location_1_s7 in Sociability
Processed time_at_location_2_s7 in Sociability
Processed time_at_location_3_s7 in Sociability
Processed time_at_location_4_s7 in Sociability
Processed time_at_location_5_s7 in Sociability
Processed time_at_location_1_s14 in Sociability
Processed time_at_location_2_s14 in Sociability
Processed time_at_location_3_s14 in Sociability
Processed time_at_location_4_s14 in Sociability
Processed time_at_location_5_s14 in Sociability
Processed num_location_clusters_m7 in Sociability
Processed num_location_clusters_m14 in Sociability
Processed num_location_clusters_s7 in Sociability
Processed num_location_clusters_s14 in Sociability
Processed loc_entropy_m7 in Sociability
Processed loc_entropy_m14 in Sociability
Processed loc_entropy_s7 in Sociability
Processed loc_entropy_s14 in Sociability
Processed travel_diameter_m7 in Sociability
Processed travel_diameter_m14 in Sociability
Processed travel_diameter_s7 in Sociability
Processed travel_diameter_s14 in Sociability
Processed ec_Location_m7 in Sociability
Processed ec_Location_m14 in Sociability
Processed ec_Location_s7 in Sociability
Processed ec_Location_s14 in Sociability
Processed total_location_duration_m7 in Sociability
Processed total_location_duration_m14 in Sociability
Processed total_location_duration_s7 in Sociability
Processed total_location_duration_s14 in Sociability

Processing Device Usage bucket...
Processed ec_DeviceDisplayStatus_m7 in Device Usage
Processed ec_DeviceDisplayStatus_m14 in Device Usage
Processed ec_DeviceDisplayStatus_s7 in Device Usage
Processed ec_DeviceDisplayStatus_s14 in Device Usage
Processed display_events_m7 in Device Usage
Processed display_events_m14 in Device Usage
Processed display_events_s7 in Device Usage
Processed display_events_s14 in Device Usage
Processed screen_unlocks_m7 in Device Usage
Processed screen_unlocks_m14 in Device Usage
Processed screen_unlocks_s7 in Device Usage
Processed screen_unlocks_s14 in Device Usage
Processed total_display_duration_m7 in Device Usage
Processed total_display_duration_m14 in Device Usage
Processed total_display_duration_s7 in Device Usage
Processed total_display_duration_s14 in Device Usage
Processed device_use_percent_m7 in Device Usage
Processed device_use_percent_m14 in Device Usage
Processed device_use_percent_s7 in Device Usage
Processed device_use_percent_s14 in Device Usage

## OLS Regression results obtained here.

In [30]:
def parse_enhanced_ols_summary(file_path):
    """Extracts full metrics from OLS summary"""
    with open(file_path, 'r') as f:
        content = f.read()
    
    metrics = {
        'r_squared': None,
        'adj_r_squared': None,
        'features': []
    }
    
    # Extract model metrics
    r2_match = re.search(r'R-squared:\s+(\d+\.\d+)', content)
    adj_r2_match = re.search(r'Adj\. R-squared:\s+(\d+\.\d+)', content)
    
    if r2_match:
        metrics['r_squared'] = float(r2_match.group(1))
    if adj_r2_match:
        metrics['adj_r_squared'] = float(adj_r2_match.group(1))
    
    # Extract feature-level metrics
    table_match = re.search(r'=+\n(.*?)\n\n', content, re.DOTALL)
    if table_match:
        rows = table_match.group(1).split('\n')[2:]
        for row in rows:
            cols = re.split(r'\s{2,}', row.strip())
            if len(cols) < 6:
                continue
            
            try:
                feature = cols[0].replace("Q('", "").replace("')", "")
                metrics['features'].append({
                    'feature': feature,
                    'coefficient': float(cols[1]),
                    'p_value': float(cols[4])
                })
            except:
                continue
    
    return metrics

def generate_feature_rankings(results_dir='regression_results'):
    all_data = []
    
    for bucket in os.listdir(results_dir):
        bucket_path = os.path.join(results_dir, bucket)
        if not os.path.isdir(bucket_path):
            continue
        
        for file in os.listdir(bucket_path):
            if file.endswith('.txt'):
                file_path = os.path.join(bucket_path, file)
                metrics = parse_enhanced_ols_summary(file_path)
                
                for feat in metrics['features']:
                    all_data.append({
                        'feature': feat['feature'],
                        'coefficient': feat['coefficient'],
                        'p_value': feat['p_value'],
                        'r_squared': metrics['r_squared'],
                        'adj_r_squared': metrics['adj_r_squared'],
                        'bucket': bucket
                    })
    
    df = pd.DataFrame(all_data)
    
    # Filter and rank
    ranked_df = (
        df[df['p_value'] < 0.05]
        .assign(abs_coeff=lambda x: x['coefficient'].abs())
        .sort_values(['abs_coeff', 'p_value'], ascending=[False, True])
        .drop('abs_coeff', axis=1)
    )
    
    return ranked_df

# Generate and display results
feature_rankings = generate_feature_rankings()
feature_rankings.shape

(385, 6)

In [31]:
feature_rankings_filter = feature_rankings[ (feature_rankings.feature != 'Intercept') & (feature_rankings.r_squared >= 0.02) ].sort_values(by='r_squared', ascending=False)
feature_rankings_filter

,feature,coefficient,p_value,r_squared,adj_r_squared,bucket
353,sleep_end_s14:C(sex)[Female]:C(age_binary)[young],1.2404,0.000,0.068,0.061,sleep
351,sleep_end_s14:C(sex)[Female]:C(age_binary)[old],1.1913,0.001,0.068,0.061,sleep
331,sleep_duration_s14:C(sex)[Female]:C(age_binary...,0.9129,0.003,0.065,0.058,sleep
333,sleep_duration_s14:C(sex)[Female]:C(age_binary...,1.1529,0.000,0.065,0.058,sleep
356,sleep_end_s7:C(sex)[Female]:C(age_binary)[old],1.1564,0.000,0.056,0.051,sleep
...,...,...,...,...,...,...
634,travel_diameter_s14:C(sex)[Male]:C(age_binary)...,-0.9218,0.000,0.020,0.017,sociability
264,screen_unlocks_m14:C(sex)[Male]:C(age_binary)[...,-1.8067,0.000,0.020,0.018,device_usage
263,screen_unlocks_m14:C(sex)[Female]:C(age_binary...,-0.3754,0.020,0.020,0.018,device_usage
319,chronotype_score_s7:C(sex)[Male]:C(age_binary)...,-0.8183,0.007,0.020,0.018,sleep
631,travel_diameter_s14:C(sex)[Female]:C(age_binar...,-2.4387,0.038,0.020,0.017,sociability

In [32]:
feature_rankings_filter[feature_rankings_filter.r_squared > 0.02]['bucket'].value_counts()

bucket
sleep           35
activity        16
device_usage    15
sociability      5
Name: count, dtype: int64

In [33]:
aashi_df_working = feature_rankings_filter[(feature_rankings_filter.bucket == 'device_usage') | (feature_rankings_filter.bucket == 'sleep')]
aashi_df_working.shape

(54, 6)

In [34]:
aashi_df_working

,feature,coefficient,p_value,r_squared,adj_r_squared,bucket
353,sleep_end_s14:C(sex)[Female]:C(age_binary)[young],1.2404,0.000,0.068,0.061,sleep
351,sleep_end_s14:C(sex)[Female]:C(age_binary)[old],1.1913,0.001,0.068,0.061,sleep
331,sleep_duration_s14:C(sex)[Female]:C(age_binary...,0.9129,0.003,0.065,0.058,sleep
333,sleep_duration_s14:C(sex)[Female]:C(age_binary...,1.1529,0.000,0.065,0.058,sleep
356,sleep_end_s7:C(sex)[Female]:C(age_binary)[old],1.1564,0.000,0.056,0.051,sleep
358,sleep_end_s7:C(sex)[Female]:C(age_binary)[young],1.1271,0.000,0.056,0.051,sleep
401,sleep_start_m14:C(sex)[Female]:C(age_binary)[old],0.7311,0.010,0.051,0.044,sleep
403,sleep_start_m14:C(sex)[Female]:C(age_binary)[y...,0.7839,0.003,0.051,0.044,sleep
336,sleep_duration_s7:C(sex)[Female]:C(age_binary)...,0.9459,0.000,0.048,0.043,sleep
338,sleep_duration_s7:C(sex)[Female]:C(age_binary)...,0.9794,0.000,0.048,0.043,sleep
413,sleep_start_s14:C(sex)[Female]:C(age_binary)[y...,0.8178,0.003,0.046,0.039,sleep
411,sleep_start_s14:C(sex)[Female]:C(age_binary)[old],0.6598,0.032,0.046,0.039,sleep
406,sleep_start_m7:C(sex)[Female]:C(age_binary)[old],0.6650,0.003,0.042,0.037,sleep
408,sleep_start_m7:C(sex)[Female]:C(age_binary)[yo...,0.6639,0.002,0.042,0.037,sleep
416,sleep_start_s7:C(sex)[Female]:C(age_binary)[old],0.8842,0.001,0.041,0.036,sleep
418,sleep_start_s7:C(sex)[Female]:C(age_binary)[yo...,0.8441,0.000,0.041,0.036,sleep
306,chronotype_score_m7:C(sex)[Female]:C(age_binar...,0.8038,0.000,0.040,0.038,sleep
308,chronotype_score_m7:C(sex)[Female]:C(age_binar...,0.9553,0.000,0.040,0.038,sleep
303,chronotype_score_m14:C(sex)[Female]:C(age_bina...,0.9740,0.000,0.040,0.038,sleep
301,chronotype_score_m14:C(sex)[Female]:C(age_bina...,0.8146,0.000,0.040,0.038,sleep
304,chronotype_score_m14:C(sex)[Male]:C(age_binary...,0.4711,0.008,0.040,0.038,sleep
309,chronotype_score_m7:C(sex)[Male]:C(age_binary)...,0.4172,0.012,0.040,0.038,sleep
302,chronotype_score_m14:C(sex)[Male]:C(age_binary...,0.3761,0.048,0.040,0.038,sleep
307,chronotype_score_m7:C(sex)[Male]:C(age_binary)...,0.3514,0.045,0.040,0.038,sleep
387,sleep_routine_index_m7:C(sex)[Male]:C(age_bina...,-1.0024,0.000,0.038,0.036,sleep
389,sleep_routine_index_m7:C(sex)[Male]:C(age_bina...,-0.9416,0.000,0.038,0.036,sleep
388,sleep_routine_index_m7:C(sex)[Female]:C(age_bi...,-0.7827,0.000,0.038,0.036,sleep
386,sleep_routine_index_m7:C(sex)[Female]:C(age_bi...,-0.8391,0.000,0.038,0.036,sleep
383,sleep_routine_index_m14:C(sex)[Female]:C(age_b...,-0.7178,0.000,0.034,0.032,sleep
381,sleep_routine_index_m14:C(sex)[Female]:C(age_b...,-0.7726,0.000,0.034,0.032,sleep
382,sleep_routine_index_m14:C(sex)[Male]:C(age_bin...,-0.8905,0.000,0.034,0.032,sleep
384,sleep_routine_index_m14:C(sex)[Male]:C(age_bin...,-0.8652,0.000,0.034,0.032,sleep
283,total_display_duration_m14:C(sex)[Female]:C(ag...,0.6715,0.000,0.030,0.028,device_usage
282,total_display_duration_m14:C(sex)[Male]:C(age_...,-0.5123,0.011,0.030,0.028,device_usage
281,total_display_duration_m14:C(sex)[Female]:C(ag...,0.2900,0.036,0.030,0.028,device_usage
286,total_display_duration_m7:C(sex)[Female]:C(age...,0.3292,0.018,0.029,0.028,device_usage
287,total_display_duration_m7:C(sex)[Male]:C(age_b...,-0.5040,0.015,0.029,0.028,device_usage
288,total_display_duration_m7:C(sex)[Female]:C(age...,0.7022,0.000,0.029,0.028,device_usage
274,screen_unlocks_s14:C(sex)[Male]:C(age_binary)[...,-2.2674,0.000,0.024,0.022,device_usage
272,screen_unlocks_s14:C(sex)[Male]:C(age_binary)[...,-1.2421,0.007,0.024,0.022,device_usage
327,sleep_duration_m7:C(sex)[Male]:C(age_binary)[old],-0.5598,0.040,0.023,0.018,sleep
393,sleep_routine_index_s14:C(sex)[Female]:C(age_b...,0.8003,0.000,0.022,0.019,sleep
232,display_events_s14:C(sex)[Male]:C(age_binary)[...,-1.6583,0.000,0.021,0.019,device_usage
222,display_events_m14:C(sex)[Male]:C(age_binary)[...,-1.5541,0.000,0.021,0.019,device_usage
278,screen_unlocks_s7:C(sex)[Female]:C(age_binary)...,-0.3211,0.048,0.021,0.019,device_usage
277,screen_unlocks_s7:C(sex)[Male]:C(age_binary)[old],-0.8864,0.041,0.021,0.019,device_usage
234,display_events_s14:C(sex)[Male]:C(age_binary)[...,-1.0279,0.001,0.021,0.019,device_usage
398,sleep_routine_index_s7:C(sex)[Female]:C(age_bi...,0.7717,0.000,0.021,0.019,sleep
224,display_events_m14:C(sex)[Male]:C(age_binary)[...,-0.7941,0.002,0.021,0.019,device_usage
279,screen_unlocks_s7:C(sex)[Male]:C(age_binary)[y...,-2.2710,0.000,0.021,0.019,device_usage
318,chronotype_score_s7:C(sex)[Female]:C(age_binar...,0.7708,0.000,0.020,0.018,sleep
264,screen_unlocks_m14:C(sex)[Male]:C(age_binary)[...,-1.8067,0.000,0.020,0.018,device_usage
263,screen_unlocks_m14:C(sex)[Female]:C(age_binary...,-0.3754,0.020,0.020,0.018,device_usage
319,chronotype_score_s7:C(sex)[Male]:C(age_binary)...,-0.8183,0.007,0.020,0.018,sleep

In [35]:
#save the df into csv file
aashi_df_working.to_csv('aashi_df_working.csv', index=False)

In [36]:
parag_df_working = feature_rankings_filter[(feature_rankings_filter.bucket == 'sociability') | (feature_rankings_filter.bucket == 'activity')]
parag_df_working.shape

(25, 6)

In [37]:
parag_df_working

,feature,coefficient,p_value,r_squared,adj_r_squared,bucket
481,time_at_home_m14:C(sex)[Female]:C(age_binary)[...,0.5099,0.001,0.029,0.027,sociability
484,time_at_home_m14:C(sex)[Male]:C(age_binary)[yo...,0.4858,0.022,0.029,0.027,sociability
483,time_at_home_m14:C(sex)[Female]:C(age_binary)[...,0.9207,0.000,0.029,0.027,sociability
194,walking_rate_s14:C(sex)[Male]:C(age_binary)[yo...,-1.0475,0.000,0.027,0.024,activity
192,walking_rate_s14:C(sex)[Male]:C(age_binary)[old],-0.9088,0.001,0.027,0.024,activity
488,time_at_home_m7:C(sex)[Female]:C(age_binary)[y...,0.8005,0.000,0.023,0.021,sociability
486,time_at_home_m7:C(sex)[Female]:C(age_binary)[old],0.4005,0.005,0.023,0.021,sociability
199,walking_rate_s7:C(sex)[Male]:C(age_binary)[young],-1.0692,0.000,0.022,0.020,activity
34,activity_percent_s14:C(sex)[Male]:C(age_binary...,-0.6893,0.001,0.022,0.019,activity
14,active_time_s14:C(sex)[Male]:C(age_binary)[young],-0.6893,0.001,0.022,0.019,activity
197,walking_rate_s7:C(sex)[Male]:C(age_binary)[old],-0.8633,0.004,0.022,0.020,activity
12,active_time_s14:C(sex)[Male]:C(age_binary)[old],-0.9242,0.004,0.022,0.019,activity
32,activity_percent_s14:C(sex)[Male]:C(age_binary...,-0.9242,0.004,0.022,0.019,activity
13,active_time_s14:C(sex)[Female]:C(age_binary)[y...,0.3919,0.017,0.022,0.019,activity
33,activity_percent_s14:C(sex)[Female]:C(age_bina...,0.3919,0.017,0.022,0.019,activity
23,activity_percent_m14:C(sex)[Female]:C(age_bina...,0.4803,0.004,0.021,0.019,activity
3,active_time_m14:C(sex)[Female]:C(age_binary)[y...,0.4803,0.004,0.021,0.019,activity
184,walking_rate_m14:C(sex)[Male]:C(age_binary)[yo...,-0.4167,0.016,0.021,0.018,activity
22,activity_percent_m14:C(sex)[Male]:C(age_binary...,-1.2928,0.000,0.021,0.019,activity
2,active_time_m14:C(sex)[Male]:C(age_binary)[old],-1.2928,0.000,0.021,0.019,activity
182,walking_rate_m14:C(sex)[Male]:C(age_binary)[old],-0.8038,0.001,0.021,0.018,activity
142,step_count_m14:C(sex)[Male]:C(age_binary)[old],-1.2947,0.000,0.020,0.018,activity
143,step_count_m14:C(sex)[Female]:C(age_binary)[yo...,0.5407,0.002,0.020,0.018,activity
634,travel_diameter_s14:C(sex)[Male]:C(age_binary)...,-0.9218,0.000,0.020,0.017,sociability
631,travel_diameter_s14:C(sex)[Female]:C(age_binar...,-2.4387,0.038,0.020,0.017,sociability

In [38]:
#save the df into csv file
parag_df_working.to_csv('parag_df_working.csv', index=False)

In [39]:
feature_rankings_filter[feature_rankings_filter['feature'].str.startswith('ste')]

,feature,coefficient,p_value,r_squared,adj_r_squared,bucket
142,step_count_m14:C(sex)[Male]:C(age_binary)[old],-1.2947,0.000,0.02,0.018,activity
143,step_count_m14:C(sex)[Female]:C(age_binary)[yo...,0.5407,0.002,0.02,0.018,activity

In [40]:
feature_rankings_filter[(feature_rankings_filter.bucket == 'device_usage') | (feature_rankings_filter.bucket == 'sleep')]

,feature,coefficient,p_value,r_squared,adj_r_squared,bucket
353,sleep_end_s14:C(sex)[Female]:C(age_binary)[young],1.2404,0.000,0.068,0.061,sleep
351,sleep_end_s14:C(sex)[Female]:C(age_binary)[old],1.1913,0.001,0.068,0.061,sleep
331,sleep_duration_s14:C(sex)[Female]:C(age_binary...,0.9129,0.003,0.065,0.058,sleep
333,sleep_duration_s14:C(sex)[Female]:C(age_binary...,1.1529,0.000,0.065,0.058,sleep
356,sleep_end_s7:C(sex)[Female]:C(age_binary)[old],1.1564,0.000,0.056,0.051,sleep
358,sleep_end_s7:C(sex)[Female]:C(age_binary)[young],1.1271,0.000,0.056,0.051,sleep
401,sleep_start_m14:C(sex)[Female]:C(age_binary)[old],0.7311,0.010,0.051,0.044,sleep
403,sleep_start_m14:C(sex)[Female]:C(age_binary)[y...,0.7839,0.003,0.051,0.044,sleep
336,sleep_duration_s7:C(sex)[Female]:C(age_binary)...,0.9459,0.000,0.048,0.043,sleep
338,sleep_duration_s7:C(sex)[Female]:C(age_binary)...,0.9794,0.000,0.048,0.043,sleep
413,sleep_start_s14:C(sex)[Female]:C(age_binary)[y...,0.8178,0.003,0.046,0.039,sleep
411,sleep_start_s14:C(sex)[Female]:C(age_binary)[old],0.6598,0.032,0.046,0.039,sleep
406,sleep_start_m7:C(sex)[Female]:C(age_binary)[old],0.6650,0.003,0.042,0.037,sleep
408,sleep_start_m7:C(sex)[Female]:C(age_binary)[yo...,0.6639,0.002,0.042,0.037,sleep
416,sleep_start_s7:C(sex)[Female]:C(age_binary)[old],0.8842,0.001,0.041,0.036,sleep
418,sleep_start_s7:C(sex)[Female]:C(age_binary)[yo...,0.8441,0.000,0.041,0.036,sleep
306,chronotype_score_m7:C(sex)[Female]:C(age_binar...,0.8038,0.000,0.040,0.038,sleep
308,chronotype_score_m7:C(sex)[Female]:C(age_binar...,0.9553,0.000,0.040,0.038,sleep
303,chronotype_score_m14:C(sex)[Female]:C(age_bina...,0.9740,0.000,0.040,0.038,sleep
301,chronotype_score_m14:C(sex)[Female]:C(age_bina...,0.8146,0.000,0.040,0.038,sleep
304,chronotype_score_m14:C(sex)[Male]:C(age_binary...,0.4711,0.008,0.040,0.038,sleep
309,chronotype_score_m7:C(sex)[Male]:C(age_binary)...,0.4172,0.012,0.040,0.038,sleep
302,chronotype_score_m14:C(sex)[Male]:C(age_binary...,0.3761,0.048,0.040,0.038,sleep
307,chronotype_score_m7:C(sex)[Male]:C(age_binary)...,0.3514,0.045,0.040,0.038,sleep
387,sleep_routine_index_m7:C(sex)[Male]:C(age_bina...,-1.0024,0.000,0.038,0.036,sleep
389,sleep_routine_index_m7:C(sex)[Male]:C(age_bina...,-0.9416,0.000,0.038,0.036,sleep
388,sleep_routine_index_m7:C(sex)[Female]:C(age_bi...,-0.7827,0.000,0.038,0.036,sleep
386,sleep_routine_index_m7:C(sex)[Female]:C(age_bi...,-0.8391,0.000,0.038,0.036,sleep
383,sleep_routine_index_m14:C(sex)[Female]:C(age_b...,-0.7178,0.000,0.034,0.032,sleep
381,sleep_routine_index_m14:C(sex)[Female]:C(age_b...,-0.7726,0.000,0.034,0.032,sleep
382,sleep_routine_index_m14:C(sex)[Male]:C(age_bin...,-0.8905,0.000,0.034,0.032,sleep
384,sleep_routine_index_m14:C(sex)[Male]:C(age_bin...,-0.8652,0.000,0.034,0.032,sleep
283,total_display_duration_m14:C(sex)[Female]:C(ag...,0.6715,0.000,0.030,0.028,device_usage
282,total_display_duration_m14:C(sex)[Male]:C(age_...,-0.5123,0.011,0.030,0.028,device_usage
281,total_display_duration_m14:C(sex)[Female]:C(ag...,0.2900,0.036,0.030,0.028,device_usage
286,total_display_duration_m7:C(sex)[Female]:C(age...,0.3292,0.018,0.029,0.028,device_usage
287,total_display_duration_m7:C(sex)[Male]:C(age_b...,-0.5040,0.015,0.029,0.028,device_usage
288,total_display_duration_m7:C(sex)[Female]:C(age...,0.7022,0.000,0.029,0.028,device_usage
274,screen_unlocks_s14:C(sex)[Male]:C(age_binary)[...,-2.2674,0.000,0.024,0.022,device_usage
272,screen_unlocks_s14:C(sex)[Male]:C(age_binary)[...,-1.2421,0.007,0.024,0.022,device_usage
327,sleep_duration_m7:C(sex)[Male]:C(age_binary)[old],-0.5598,0.040,0.023,0.018,sleep
393,sleep_routine_index_s14:C(sex)[Female]:C(age_b...,0.8003,0.000,0.022,0.019,sleep
232,display_events_s14:C(sex)[Male]:C(age_binary)[...,-1.6583,0.000,0.021,0.019,device_usage
222,display_events_m14:C(sex)[Male]:C(age_binary)[...,-1.5541,0.000,0.021,0.019,device_usage
278,screen_unlocks_s7:C(sex)[Female]:C(age_binary)...,-0.3211,0.048,0.021,0.019,device_usage
277,screen_unlocks_s7:C(sex)[Male]:C(age_binary)[old],-0.8864,0.041,0.021,0.019,device_usage
234,display_events_s14:C(sex)[Male]:C(age_binary)[...,-1.0279,0.001,0.021,0.019,device_usage
398,sleep_routine_index_s7:C(sex)[Female]:C(age_bi...,0.7717,0.000,0.021,0.019,sleep
224,display_events_m14:C(sex)[Male]:C(age_binary)[...,-0.7941,0.002,0.021,0.019,device_usage
279,screen_unlocks_s7:C(sex)[Male]:C(age_binary)[y...,-2.2710,0.000,0.021,0.019,device_usage
318,chronotype_score_s7:C(sex)[Female]:C(age_binar...,0.7708,0.000,0.020,0.018,sleep
264,screen_unlocks_m14:C(sex)[Male]:C(age_binary)[...,-1.8067,0.000,0.020,0.018,device_usage
263,screen_unlocks_m14:C(sex)[Female]:C(age_binary...,-0.3754,0.020,0.020,0.018,device_usage
319,chronotype_score_s7:C(sex)[Male]:C(age_binary)...,-0.8183,0.007,0.020,0.018,sleep

In [41]:
df.sleep_duration_m7.isna().sum()

2133

In [42]:
750/2

375.0

In [48]:
feature_buckets

{'Sleep': ['sleep_duration_m7',
  'sleep_duration_m14',
  'sleep_duration_s7',
  'sleep_duration_s14',
  'sleep_start_m7',
  'sleep_start_m14',
  'sleep_start_s7',
  'sleep_start_s14',
  'sleep_end_m7',
  'sleep_end_m14',
  'sleep_end_s7',
  'sleep_end_s14',
  'sleep_interruptions_m7',
  'sleep_interruptions_m14',
  'sleep_interruptions_s7',
  'sleep_interruptions_s14',
  'sleep_routine_index_m7',
  'sleep_routine_index_m14',
  'sleep_routine_index_s7',
  'sleep_routine_index_s14',
  'chronotype_score_m7',
  'chronotype_score_m14',
  'chronotype_score_s7',
  'chronotype_score_s14'],
 'Activity': ['active_time_m7',
  'active_time_m14',
  'active_time_s7',
  'active_time_s14',
  'activity_percent_m7',
  'activity_percent_m14',
  'activity_percent_s7',
  'activity_percent_s14',
  'ec_Activity_m7',
  'ec_Activity_m14',
  'ec_Activity_s7',
  'ec_Activity_s14',
  'ec_PedometerData_m7',
  'ec_PedometerData_m14',
  'ec_PedometerData_s7',
  'ec_PedometerData_s14',
  'step_count_m7',
  'step_count_m14',
  'step_count_s7',
  'step_count_s14',
  'steps_most_active_10h_m7',
  'steps_most_active_10h_m14',
  'steps_most_active_10h_s7',
  'steps_most_active_10h_s14',
  'steps_least_active_5h_m7',
  'steps_least_active_5h_m14',
  'steps_least_active_5h_s7',
  'steps_least_active_5h_s14',
  'steps_relative_amplitude_m7',
  'steps_relative_amplitude_m14',
  'steps_relative_amplitude_s7',
  'steps_relative_amplitude_s14',
  'walking_rate_m7',
  'walking_rate_m14',
  'walking_rate_s7',
  'walking_rate_s14',
  'total_activity_duration_m7',
  'total_activity_duration_m14',
  'total_activity_duration_s7',
  'total_activity_duration_s14'],
 'Sociability': ['time_at_home_m7',
  'time_at_home_m14',
  'time_at_home_s7',
  'time_at_home_s14',
  'time_at_location_1_m7',
  'time_at_location_2_m7',
  'time_at_location_3_m7',
  'time_at_location_4_m7',
  'time_at_location_5_m7',
  'time_at_location_1_m14',
  'time_at_location_2_m14',
  'time_at_location_3_m14',
  'time_at_location_4_m14',
  'time_at_location_5_m14',
  'time_at_location_1_s7',
  'time_at_location_2_s7',
  'time_at_location_3_s7',
  'time_at_location_4_s7',
  'time_at_location_5_s7',
  'time_at_location_1_s14',
  'time_at_location_2_s14',
  'time_at_location_3_s14',
  'time_at_location_4_s14',
  'time_at_location_5_s14',
  'num_location_clusters_m7',
  'num_location_clusters_m14',
  'num_location_clusters_s7',
  'num_location_clusters_s14',
  'loc_entropy_m7',
  'loc_entropy_m14',
  'loc_entropy_s7',
  'loc_entropy_s14',
  'travel_diameter_m7',
  'travel_diameter_m14',
  'travel_diameter_s7',
  'travel_diameter_s14',
  'ec_Location_m7',
  'ec_Location_m14',
  'ec_Location_s7',
  'ec_Location_s14',
  'total_location_duration_m7',
  'total_location_duration_m14',
  'total_location_duration_s7',
  'total_location_duration_s14'],
 'Device Usage': ['ec_DeviceDisplayStatus_m7',
  'ec_DeviceDisplayStatus_m14',
  'ec_DeviceDisplayStatus_s7',
  'ec_DeviceDisplayStatus_s14',
  'display_events_m7',
  'display_events_m14',
  'display_events_s7',
  'display_events_s14',
  'screen_unlocks_m7',
  'screen_unlocks_m14',
  'screen_unlocks_s7',
  'screen_unlocks_s14',
  'total_display_duration_m7',
  'total_display_duration_m14',
  'total_display_duration_s7',
  'total_display_duration_s14',
  'device_use_percent_m7',
  'device_use_percent_m14',
  'device_use_percent_s7',
  'device_use_percent_s14'],
 'Demographic': ['age_bucket',
  'age_num',
  'sex',
  'gender',
  'housemates',
  'occupation',
  'school',
  'phone_carry',
  'full_time',
  'ethnicity',
  'ethnicity_white',
  'age_binary',
  'chronotype'],
 'Other': ['user_id',
  'ts',
  'deployment',
  'ec_total_m7',
  'ec_total_m14',
  'ec_total_s7',
  'ec_total_s14'],
 'Target': ['phq_q1',
  'phq_q2',
  'phq_q3',
  'phq_q4',
  'phq_q5',
  'phq_q6',
  'phq_q7',
  'phq_q8',
  'phq_q9',
  'phq2_total',
  'phq8_total',
  'phq9_total',
  'phq_category']}

In [86]:
feature_buckets['Sleep']

['sleep_duration_m7',
 'sleep_duration_m14',
 'sleep_duration_s7',
 'sleep_duration_s14',
 'sleep_start_m7',
 'sleep_start_m14',
 'sleep_start_s7',
 'sleep_start_s14',
 'sleep_end_m7',
 'sleep_end_m14',
 'sleep_end_s7',
 'sleep_end_s14',
 'sleep_interruptions_m7',
 'sleep_interruptions_m14',
 'sleep_interruptions_s7',
 'sleep_interruptions_s14',
 'sleep_routine_index_m7',
 'sleep_routine_index_m14',
 'sleep_routine_index_s7',
 'sleep_routine_index_s14',
 'chronotype_score_m7',
 'chronotype_score_m14',
 'chronotype_score_s7',
 'chronotype_score_s14']

In [64]:
results = {}

# Analyze missingness for each bucket
for bucket_name, cols in feature_buckets.items():
    # Filter columns that exist in the DataFrame
    valid_cols = [c for c in cols if c in df.columns]
    
    # Flag days with ANY missing data in this bucket
    df[f'missing_{bucket_name}'] = df[valid_cols].isnull().any(axis=1)
    
    # Compute missing proportion per user for this bucket
    missing_proportion = df.groupby('user_id')[f'missing_{bucket_name}'].mean()
    results[bucket_name] = missing_proportion

# Combine results into a DataFrame
missing_by_bucket = pd.DataFrame(results)
missing_by_bucket

,Sleep,Activity,Sociability,Device Usage,Demographic,Other,Target
user_id,,,,,,,
us-east-1:db841a21-c400-c09b-cb33-144516a80231,0.666667,0.333333,0.333333,0.166667,1.0,0.166667,0.0
us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268,1.000000,1.000000,1.000000,1.000000,1.0,0.166667,0.0
us-east-1:db841a21-c402-c83f-fadf-41f6d4271053,1.000000,0.500000,0.500000,0.500000,1.0,0.500000,0.0
us-east-1:db841a21-c402-c9e0-501c-45fd38e3b5e3,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,0.0
us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1,1.000000,0.500000,0.750000,1.000000,1.0,0.250000,0.0
...,...,...,...,...,...,...,...
us-east-1:db841a21-c4ff-c644-6a64-0583e73a79d9,1.000000,0.800000,0.800000,0.800000,1.0,0.200000,0.0
us-east-1:db841a21-c4ff-c868-02a6-5cfff64a075a,1.000000,0.333333,0.500000,0.500000,1.0,0.166667,0.0
us-east-1:db841a21-c4ff-cb45-cad0-4821d631eb58,0.833333,0.333333,0.500000,0.166667,1.0,0.166667,0.0
us-east-1:db841a21-c4ff-cb63-a6da-f45b3c81a5c5,0.666667,0.666667,1.000000,0.500000,1.0,0.166667,0.0
us-east-1:db841a21-c4ff-cf28-acdc-a8ab36af1fa3,0.500000,0.333333,0.666667,0.333333,1.0,0.166667,0.0

In [101]:
a = df[df.user_id == 'us-east-1:db841a21-c400-c09b-cb33-144516a80231'][['user_id', 'ts', 'sleep_duration_m7', 'sleep_duration_m14', 'sleep_duration_s7', 'sleep_duration_s14', 'sleep_start_m7', 'sleep_start_m14', 'sleep_start_s7', 'sleep_start_s14', 'sleep_end_m7', 'sleep_end_m14', 'sleep_end_s7', 'sleep_end_s14', 'sleep_interruptions_m7', 'sleep_interruptions_m14', 'sleep_interruptions_s7', 'sleep_interruptions_s14', 'sleep_routine_index_m7', 'sleep_routine_index_m14', 'sleep_routine_index_s7', 'sleep_routine_index_s14', 'chronotype_score_m7', 'chronotype_score_m14', 'chronotype_score_s7', 'chronotype_score_s14']]
a

,user_id,ts,sleep_duration_m7,sleep_duration_m14,sleep_duration_s7,sleep_duration_s14,sleep_start_m7,sleep_start_m14,sleep_start_s7,sleep_start_s14,...,sleep_interruptions_s7,sleep_interruptions_s14,sleep_routine_index_m7,sleep_routine_index_m14,sleep_routine_index_s7,sleep_routine_index_s14,chronotype_score_m7,chronotype_score_m14,chronotype_score_s7,chronotype_score_s14
456,us-east-1:db841a21-c400-c09b-cb33-144516a80231,2024-05-04 14:13:46.887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,us-east-1:db841a21-c400-c09b-cb33-144516a80231,2024-05-18 14:39:27.530,32057.142857,NaN,5605.609435,NaN,21000.000000,NaN,3766.961640,NaN,...,0.0,NaN,0.928241,NaN,0.020512,NaN,1.425714,NaN,0.047909,NaN
1322,us-east-1:db841a21-c400-c09b-cb33-144516a80231,2024-06-01 14:39:35.855,30042.857143,30042.857143,4296.842695,6041.231954,22285.714286,21964.285714,2953.206490,5573.095693,...,0.0,0.0,0.907655,0.914641,0.024392,0.025047,1.592857,1.547143,0.013801,0.090590
1847,us-east-1:db841a21-c400-c09b-cb33-144516a80231,2024-06-17 23:17:52.098,32528.571429,NaN,3722.326461,NaN,20957.142857,NaN,2629.231284,NaN,...,0.0,NaN,0.916700,0.925017,0.010720,0.013616,1.540000,1.539286,0.014142,0.029733
2455,us-east-1:db841a21-c400-c09b-cb33-144516a80231,2024-07-09 12:28:52.414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.935317,0.932482,0.007820,0.009945,1.531429,1.562143,0.047409,0.045434
2594,us-east-1:db841a21-c400-c09b-cb33-144516a80231,2024-07-16 14:19:11.857,32400.000000,33428.571429,2754.995463,3643.419478,20528.571429,19928.571429,2141.428095,2013.198210,...,0.0,0.0,0.942874,0.937847,0.013081,0.012496,1.464286,1.490714,0.022254,0.040281

In [102]:
for i in a.index:
    print(a.loc[i])

user_id                    us-east-1:db841a21-c400-c09b-cb33-144516a80231
ts                                             2024-05-04 14:13:46.887000
sleep_duration_m7                                                     NaN
sleep_duration_m14                                                    NaN
sleep_duration_s7                                                     NaN
sleep_duration_s14                                                    NaN
sleep_start_m7                                                        NaN
sleep_start_m14                                                       NaN
sleep_start_s7                                                        NaN
sleep_start_s14                                                       NaN
sleep_end_m7                                                          NaN
sleep_end_m14                                                         NaN
sleep_end_s7                                                          NaN
sleep_end_s14                                                         NaN
sleep_interruptions_m7                                                NaN
sleep_interruptions_m14                                               NaN
sleep_interruptions_s7                                                NaN
sleep_interruptions_s14                                               NaN
sleep_routine_index_m7                                                NaN
sleep_routine_index_m14                                               NaN
sleep_routine_index_s7                                                NaN
sleep_routine_index_s14                                               NaN
chronotype_score_m7                                                   NaN
chronotype_score_m14                                                  NaN
chronotype_score_s7                                                   NaN
chronotype_score_s14                                                  NaN
Name: 456, dtype: object
user_id                    us-east-1:db841a21-c400-c09b-cb33-144516a80231
ts                                             2024-05-18 14:39:27.530000
sleep_duration_m7                                            32057.142857
sleep_duration_m14                                                    NaN
sleep_duration_s7                                             5605.609435
sleep_duration_s14                                                    NaN
sleep_start_m7                                                    21000.0
sleep_start_m14                                                       NaN
sleep_start_s7                                                 3766.96164
sleep_start_s14                                                       NaN
sleep_end_m7                                                 53057.142857
sleep_end_m14                                                         NaN
sleep_end_s7                                                  2816.532823
sleep_end_s14                                                         NaN
sleep_interruptions_m7                                                0.0
sleep_interruptions_m14                                               NaN
sleep_interruptions_s7                                                0.0
sleep_interruptions_s14                                               NaN
sleep_routine_index_m7                                           0.928241
sleep_routine_index_m14                                               NaN
sleep_routine_index_s7                                           0.020512
sleep_routine_index_s14                                               NaN
chronotype_score_m7                                              1.425714
chronotype_score_m14                                                  NaN
chronotype_score_s7                                              0.047909
chronotype_score_s14                                                  NaN
Name: 893, dtype: object
user_id                    us-east-1:db841a21-c400-c09b-cb33-144516a80231
ts                                             2024-06-01 14:39:35.855000
sleep_duration_m7                                            30042.857143
sleep_duration_m14                                           30042.857143
sleep_duration_s7                                             4296.842695
sleep_duration_s14                                            6041.231954
sleep_start_m7                                               22285.714286
sleep_start_m14                                              21964.285714
sleep_start_s7                                                 2953.20649
sleep_start_s14                                               5573.095693
sleep_end_m7                                                 52328.571429
sleep_end_m14                                                52007.142857
sleep_end_s7                                                  2303.413616
sleep_end_s14                                                 2110.218467
sleep_interruptions_m7                                                0.0
sleep_interruptions_m14                                               0.0
sleep_interruptions_s7                                                0.0
sleep_interruptions_s14                                               0.0
sleep_routine_index_m7                                           0.907655
sleep_routine_index_m14                                          0.914641
sleep_routine_index_s7                                           0.024392
sleep_routine_index_s14                                          0.025047
chronotype_score_m7                                              1.592857
chronotype_score_m14                                             1.547143
chronotype_score_s7                                              0.013801
chronotype_score_s14                                              0.09059
Name: 1322, dtype: object
user_id                    us-east-1:db841a21-c400-c09b-cb33-144516a80231
ts                                             2024-06-17 23:17:52.098000
sleep_duration_m7                                            32528.571429
sleep_duration_m14                                                    NaN
sleep_duration_s7                                             3722.326461
sleep_duration_s14                                                    NaN
sleep_start_m7                                               20957.142857
sleep_start_m14                                                       NaN
sleep_start_s7                                                2629.231284
sleep_start_s14                                                       NaN
sleep_end_m7                                                 53485.714286
sleep_end_m14                                                         NaN
sleep_end_s7                                                  3449.844717
sleep_end_s14                                                         NaN
sleep_interruptions_m7                                                0.0
sleep_interruptions_m14                                               NaN
sleep_interruptions_s7                                                0.0
sleep_interruptions_s14                                               NaN
sleep_routine_index_m7                                             0.9167
sleep_routine_index_m14                                          0.925017
sleep_routine_index_s7                                            0.01072
sleep_routine_index_s14                                          0.013616
chronotype_score_m7                                                  1.54
chronotype_score_m14                                             1.539286
chronotype_score_s7                                              0.014142
chronotype_score_s14                                             0.029733
Name: 1847, dtype: object
user_id                    us-east-1:db841a21-c400-c09b-cb33-144516a80231
ts                                             2024-07-09 12:28:52.414000
sleep_duration_m7                                                     NaN
sleep_duration_m14                                                    NaN
sleep_duration_s7                                                     NaN
sleep_duration_s14                                                    NaN
sleep_start_m7                                                        NaN
sleep_start_m14                                                       NaN
sleep_start_s7                                                        NaN
sleep_start_s14                                                       NaN
sleep_end_m7                                                          NaN
sleep_end_m14                                                         NaN
sleep_end_s7                                                          NaN
sleep_end_s14                                                         NaN
sleep_interruptions_m7                                                NaN
sleep_interruptions_m14                                               NaN
sleep_interruptions_s7                                                NaN
sleep_interruptions_s14                                               NaN
sleep_routine_index_m7                                           0.935317
sleep_routine_index_m14                                          0.932482
sleep_routine_index_s7                                            0.00782
sleep_routine_index_s14                                          0.009945
chronotype_score_m7                                              1.531429
chronotype_score_m14                                             1.562143
chronotype_score_s7                                              0.047409
chronotype_score_s14                                             0.045434
Name: 2455, dtype: object
user_id                    us-east-1:db841a21-c400-c09b-cb33-144516a80231
ts                                             2024-07-16 14:19:11.857000
sleep_duration_m7                                                 32400.0
sleep_duration_m14                                           33428.571429
sleep_duration_s7                                             2754.995463
sleep_duration_s14                                            3643.419478
sleep_start_m7                                               20528.571429
sleep_start_m14                                              19928.571429
sleep_start_s7                                                2141.428095
sleep_start_s14                                                2013.19821
sleep_end_m7                                                 52928.571429
sleep_end_m14                                                53357.142857
sleep_end_s7                                                  1872.355278
sleep_end_s14                                                 2786.703121
sleep_interruptions_m7                                                0.0
sleep_interruptions_m14                                               0.0
sleep_interruptions_s7                                                0.0
sleep_interruptions_s14                                               0.0
sleep_routine_index_m7                                           0.942874
sleep_routine_index_m14                                          0.937847
sleep_routine_index_s7                                           0.013081
sleep_routine_index_s14                                          0.012496
chronotype_score_m7                                              1.464286
chronotype_score_m14                                             1.490714
chronotype_score_s7                                              0.022254
chronotype_score_s14                                             0.040281
Name: 2594, dtype: object

In [73]:
# Example: Find users with >80% missing days in the 'sleep' bucket
threshold = 0.3
problematic_users_sleep = missing_by_bucket[missing_by_bucket['Sleep'] > threshold].index.tolist()
problematic_users_sleep

['us-east-1:db841a21-c400-c09b-cb33-144516a80231',
 'us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268',
 'us-east-1:db841a21-c402-c83f-fadf-41f6d4271053',
 'us-east-1:db841a21-c402-c9e0-501c-45fd38e3b5e3',
 'us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1',
 'us-east-1:db841a21-c403-c5dc-0f8d-fdaad2b0c8c0',
 'us-east-1:db841a21-c403-ce6b-e911-a2865b0f3c9a',
 'us-east-1:db841a21-c404-c304-c2e4-572d6e178c68',
 'us-east-1:db841a21-c404-c440-4199-c74ef9e1b19d',
 'us-east-1:db841a21-c404-c761-77c2-8cab76aaa00a',
 'us-east-1:db841a21-c404-c936-f3ee-306b897c08c3',
 'us-east-1:db841a21-c404-cb9a-95f4-a148924f855c',
 'us-east-1:db841a21-c404-cff1-369e-124fb7a439b3',
 'us-east-1:db841a21-c405-c5e7-6ec9-d6661f205f9d',
 'us-east-1:db841a21-c405-ccc6-81c9-f5a0ba288ba5',
 'us-east-1:db841a21-c406-c96a-f0ab-fc0e42567bc7',
 'us-east-1:db841a21-c406-ccf9-7dce-71496e2b0b9c',
 'us-east-1:db841a21-c407-c0e5-a83d-7cd2cd6853b7',
 'us-east-1:db841a21-c408-c249-6b08-c8edb187f610',
 'us-east-1:db841a21-c408-c62c-ac1a-dc288a4bd03b',
 'us-east-1:db841a21-c408-c98a-b252-0543d89cb687',
 'us-east-1:db841a21-c408-cd14-7bab-1f27128bcada',
 'us-east-1:db841a21-c408-cdbc-0186-53810b8a48a0',
 'us-east-1:db841a21-c408-cf7e-bc70-6a90bc7247a6',
 'us-east-1:db841a21-c409-c20a-58b2-003bbbccf6ba',
 'us-east-1:db841a21-c409-c321-cd8b-302b9a29beb4',
 'us-east-1:db841a21-c409-ce44-5617-ed676e3e5cfd',
 'us-east-1:db841a21-c40a-c99c-127f-9719c024ed4f',
 'us-east-1:db841a21-c40a-ceea-3f41-c42bb0c5952b',
 'us-east-1:db841a21-c40b-c9e0-42a3-cc4aeacb0835',
 'us-east-1:db841a21-c40c-c0b3-ddb4-433a32849e70',
 'us-east-1:db841a21-c40c-cb29-61ad-8a1f6d903d09',
 'us-east-1:db841a21-c40c-cefd-8940-540bef858816',
 'us-east-1:db841a21-c40c-cf05-e996-a8d0237aab9d',
 'us-east-1:db841a21-c40d-c23e-0964-22c61c64f431',
 'us-east-1:db841a21-c40d-caad-8a4e-eeee57c9dd5d',
 'us-east-1:db841a21-c40d-ccd3-2aa1-59a17ddeabd6',
 'us-east-1:db841a21-c40e-c22d-b761-8771da86141a',
 'us-east-1:db841a21-c40e-ca56-d651-8007780a9ef0',
 'us-east-1:db841a21-c40e-cbbe-c2d9-5cc458dfed0a',
 'us-east-1:db841a21-c40f-c39f-aa6c-92ccb087cdd5',
 'us-east-1:db841a21-c40f-c51a-12de-41e5423ce4e7',
 'us-east-1:db841a21-c40f-c8a8-a41e-d47ce3fe7e82',
 'us-east-1:db841a21-c410-c89c-0ae5-5b7cfcfbb9cd',
 'us-east-1:db841a21-c410-cd02-66da-cc03f30d5063',
 'us-east-1:db841a21-c410-cd25-d9b2-17193ebd9269',
 'us-east-1:db841a21-c410-cf92-a396-85539744f102',
 'us-east-1:db841a21-c412-c410-11c4-ed48647914c5',
 'us-east-1:db841a21-c414-c2f5-37b0-e0836c7d2c38',
 'us-east-1:db841a21-c414-c4ca-6b7c-e00b025b00dd',
 'us-east-1:db841a21-c414-c54b-38ca-8fe3b05aae27',
 'us-east-1:db841a21-c414-cdd4-a0c3-8c07e9e58dba',
 'us-east-1:db841a21-c415-c726-d4a6-371349a69794',
 'us-east-1:db841a21-c415-ce0c-3b1a-d23c7a517f03',
 'us-east-1:db841a21-c415-ce51-5853-c6b35dd9a816',
 'us-east-1:db841a21-c416-cd9d-a8ef-a6cd912a2c9e',
 'us-east-1:db841a21-c417-c47e-8c89-66f1c5053baa',
 'us-east-1:db841a21-c418-c4c6-9475-f8e4cb00209b',
 'us-east-1:db841a21-c418-ca02-8c22-b67884725045',
 'us-east-1:db841a21-c418-ca2b-497c-7aa97486abbe',
 'us-east-1:db841a21-c418-ce8a-4c80-4961e52ddb80',
 'us-east-1:db841a21-c419-c069-8c97-04c23d32f053',
 'us-east-1:db841a21-c419-c9e1-016a-6025f1cccae2',
 'us-east-1:db841a21-c41a-c163-8486-5b2485c2c6ef',
 'us-east-1:db841a21-c41a-c82a-69e6-d78ae7501cc9',
 'us-east-1:db841a21-c41a-cdf1-a0e7-2cc2c61d72e2',
 'us-east-1:db841a21-c41b-c866-3780-4af2a72dc97f',
 'us-east-1:db841a21-c41c-c68a-e2ff-765cc3804796',
 'us-east-1:db841a21-c41d-c740-7a8e-6721246d452e',
 'us-east-1:db841a21-c41d-cb0d-39cf-1928c42a4242',
 'us-east-1:db841a21-c41e-c41b-028c-41522121768b',
 'us-east-1:db841a21-c41e-c84e-176f-15f3643d8507',
 'us-east-1:db841a21-c41e-cf95-099c-1f1d46ccaa53',
 'us-east-1:db841a21-c41f-ccd0-a5e3-700d8e3189a2',
 'us-east-1:db841a21-c41f-cdf0-a318-973e38f0b767',
 'us-east-1:db841a21-c41f-ce6c-8fb1-8d2c85b75afa',
 'us-east-1:db841a21-c420-c4ad-0a48-50742d3f72bb',
 'us-east-1:db841a21-c420-c7fb-2099-3d55e736b8b8',
 'us-east-1:db841a21-c420-c8e2-c5a6-de258e978da9',
 'us-east-1:db841a21-c421-c6eb-cdb5-ef1e362bd0b1',
 'us-east-1:db841a21-c424-c239-381b-89ce92763aa8',
 'us-east-1:db841a21-c424-c6e4-87d4-9532446c23b4',
 'us-east-1:db841a21-c424-c9ed-d615-5b4ba3416c76',
 'us-east-1:db841a21-c425-c0d1-d258-6b83a7c95ca2',
 'us-east-1:db841a21-c425-c87f-7af3-a5a14b993a02',
 'us-east-1:db841a21-c425-ca6b-81ce-c07696657f59',
 'us-east-1:db841a21-c426-c0f6-7d23-f944db9ce22d',
 'us-east-1:db841a21-c426-c1e3-6940-96151654305d',
 'us-east-1:db841a21-c426-c304-48df-8420b157f008',
 'us-east-1:db841a21-c426-c661-57e2-704b854fbcf6',
 'us-east-1:db841a21-c427-c29a-4f33-4bb65b9333ff',
 'us-east-1:db841a21-c427-c3b9-7de9-909624118ff9',
 'us-east-1:db841a21-c427-c4d2-cc8a-893f2f3e554b',
 'us-east-1:db841a21-c427-cd89-5089-19b6f437097b',
 'us-east-1:db841a21-c428-c1cd-131c-a45ad6220557',
 'us-east-1:db841a21-c42a-c80d-5975-1c9d04643f5e',
 'us-east-1:db841a21-c42a-c8ca-91a6-fef7b7867bf5',
 'us-east-1:db841a21-c42b-c769-bb50-2bd194cdc973',
 'us-east-1:db841a21-c42b-c8a1-018a-aaea8824803d',
 'us-east-1:db841a21-c42b-cc98-1ce4-8b4959b46797',
 'us-east-1:db841a21-c42c-c048-edc9-b33d06769b8a',
 'us-east-1:db841a21-c42c-c4c3-249a-8eb400723e7e',
 'us-east-1:db841a21-c42e-c314-d622-ec5f1dba1aea',
 'us-east-1:db841a21-c42e-c9ae-0e93-38b537edc422',
 'us-east-1:db841a21-c42e-cc7c-4b43-b66c4fa3872b',
 'us-east-1:db841a21-c42e-ce09-be44-a8aa45492ea7',
 'us-east-1:db841a21-c42f-c0da-e128-0a36daa25089',
 'us-east-1:db841a21-c42f-c1bf-2de5-7d8877103171',
 'us-east-1:db841a21-c42f-c6ec-693c-36da2d0b4241',
 'us-east-1:db841a21-c42f-c776-b679-d8893337629d',
 'us-east-1:db841a21-c42f-ce37-8f55-4cbbd7167e10',
 'us-east-1:db841a21-c42f-cff6-84f8-0404b495fe50',
 'us-east-1:db841a21-c430-c328-c5be-5ddb2cdac566',
 'us-east-1:db841a21-c430-c4a2-f115-d7304b6c613c',
 'us-east-1:db841a21-c430-cbe5-381d-0eb8ede15ecd',
 'us-east-1:db841a21-c430-cfca-cbe0-2d4bac0c6141',
 'us-east-1:db841a21-c431-c3b6-a41b-d80dd242f8e3',
 'us-east-1:db841a21-c431-c773-b4e1-85db3a9066f8',
 'us-east-1:db841a21-c431-c7fe-d70e-967a4d373afa',
 'us-east-1:db841a21-c431-c97c-cfca-d51427cee299',
 'us-east-1:db841a21-c432-c05a-f9d9-6ce246ea77ec',
 'us-east-1:db841a21-c432-cdb4-cc47-21550ead8360',
 'us-east-1:db841a21-c433-c55e-c10d-b4d4aab63900',
 'us-east-1:db841a21-c433-cebe-7246-ab5047971173',
 'us-east-1:db841a21-c433-cfc6-76ee-a95863ef8b72',
 'us-east-1:db841a21-c434-c0ec-2958-e297cfa424b7',
 'us-east-1:db841a21-c434-c1f2-4d7d-0b739e027955',
 'us-east-1:db841a21-c434-c827-b398-f9da8a15fb2d',
 'us-east-1:db841a21-c434-c8a2-28ba-b7fdd7274a97',
 'us-east-1:db841a21-c434-cbb0-ba5d-91c69b2ffbb1',
 'us-east-1:db841a21-c434-ce72-bf43-a3a7937872c2',
 'us-east-1:db841a21-c434-cebe-ce63-1fcf294c8420',
 'us-east-1:db841a21-c435-c649-eaa4-825a17b19e14',
 'us-east-1:db841a21-c435-cc3d-33c9-a6a9c0ec9fd9',
 'us-east-1:db841a21-c436-c614-da75-c968e2c4315d',
 'us-east-1:db841a21-c436-ccdd-fc2a-d89f5b3dbfd4',
 'us-east-1:db841a21-c438-c24c-2492-fee6bce49000',
 'us-east-1:db841a21-c438-c76a-5078-c47a75e6b0c3',
 'us-east-1:db841a21-c438-cc82-3a21-9665f5d1bdb6',
 'us-east-1:db841a21-c439-c0e8-e8ad-a3ff25e568c8',
 'us-east-1:db841a21-c439-c1e0-45f3-7db03e1ecaaf',
 'us-east-1:db841a21-c439-c63f-5d36-a0edf441a890',
 'us-east-1:db841a21-c439-ca52-2cde-e7da3aee42b3',
 'us-east-1:db841a21-c439-cc3f-2c82-bd90d0cee921',
 'us-east-1:db841a21-c43a-c301-6e75-a36024ae9141',
 'us-east-1:db841a21-c43a-ca06-b7ac-b3b48db28b49',
 'us-east-1:db841a21-c43a-cbc7-a183-f2f87fd48dd7',
 'us-east-1:db841a21-c43b-c590-26cd-6f6c09601472',
 'us-east-1:db841a21-c43b-cbee-d9c2-b1d7522e1b40',
 'us-east-1:db841a21-c43c-c8ae-8ced-ce1458e58483',
 'us-east-1:db841a21-c43c-c8b3-fd13-77269618c488',
 'us-east-1:db841a21-c43d-c502-4c84-9ecd55016306',
 'us-east-1:db841a21-c43e-ce6e-20ae-244268e87e34',
 'us-east-1:db841a21-c43f-c79e-a8d2-30031cde4786',
 'us-east-1:db841a21-c440-cd9e-582c-5fd3901413a8',
 'us-east-1:db841a21-c441-c3ca-ac58-b274980e67ea',
 'us-east-1:db841a21-c441-cc44-def9-1915f32a3d78',
 'us-east-1:db841a21-c442-c341-b369-7fa1b2dcde58',
 'us-east-1:db841a21-c442-cdd1-8c5b-617726c2b084',
 'us-east-1:db841a21-c443-c4fe-830b-8fb5f3d98b76',
 'us-east-1:db841a21-c443-c91d-c665-07cb5bb8bd1a',
 'us-east-1:db841a21-c443-cde9-ee0e-a59e7f466f0b',
 'us-east-1:db841a21-c444-c213-1319-55736c143811',
 'us-east-1:db841a21-c444-cee6-4ba1-a9d51fb03085',
 'us-east-1:db841a21-c445-c0eb-66bb-d377eedf835d',
 'us-east-1:db841a21-c445-c6f3-38bf-400795de4ba0',
 'us-east-1:db841a21-c446-c0d4-8756-da6fd274ac8f',
 'us-east-1:db841a21-c446-c3af-f53c-4b36216c1ff6',
 'us-east-1:db841a21-c447-cbf6-693d-6bb00e01b2b5',
 'us-east-1:db841a21-c447-cf7a-85f4-c42a7cffab11',
 'us-east-1:db841a21-c448-c830-7049-62c4c4997a3c',
 'us-east-1:db841a21-c448-c970-7da6-45eabf6035c4',
 'us-east-1:db841a21-c449-c7b8-6915-1384f19cd11c',
 'us-east-1:db841a21-c449-c8d6-1b04-62419e021f4b',
 'us-east-1:db841a21-c44a-cb2f-dd3c-0eae2415f2dc',
 'us-east-1:db841a21-c44b-c0d1-d14f-45303e5fc49e',
 'us-east-1:db841a21-c44b-c913-213d-08df70b78ff3',
 'us-east-1:db841a21-c44b-c97f-1b7c-05177705f256',
 'us-east-1:db841a21-c44b-ce96-3fef-c8785157c6cb',
 'us-east-1:db841a21-c44b-cf4e-d6ae-a0c8f3a0d35f',
 'us-east-1:db841a21-c44c-c3a6-8366-7e3e6f29d92e',
 'us-east-1:db841a21-c44c-c6b5-69fa-0f35d67f9123',
 'us-east-1:db841a21-c44c-c706-5368-8c302d946912',
 'us-east-1:db841a21-c44d-c65e-ce01-5503ffa59254',
 'us-east-1:db841a21-c44e-c120-4b4e-fc3e107df924',
 'us-east-1:db841a21-c44e-c4ff-c770-7c8b5a3c5bf6',
 'us-east-1:db841a21-c44f-c40d-1934-18d5d1ec7994',
 'us-east-1:db841a21-c44f-c4b8-bf00-5dd55b758e86',
 'us-east-1:db841a21-c44f-c614-abc9-233033169d27',
 'us-east-1:db841a21-c44f-cf74-074e-451db9c78ccb',
 'us-east-1:db841a21-c450-ccb3-89dc-78c81f62a8b1',
 'us-east-1:db841a21-c451-c9e8-12c7-2d6c38f86a3a',
 'us-east-1:db841a21-c451-cb34-a252-770fd42144b3',
 'us-east-1:db841a21-c452-c123-4d4a-e94a8e1613b7',
 'us-east-1:db841a21-c452-c287-24ca-ec4c9ff9af2b',
 'us-east-1:db841a21-c452-c4d2-5236-021895e6422b',
 'us-east-1:db841a21-c452-c776-e250-ea18c50ea5dc',
 'us-east-1:db841a21-c452-cbd9-5bac-1bdb7d2d2906',
 'us-east-1:db841a21-c453-c16f-9058-cf3a6d899ec5',
 'us-east-1:db841a21-c453-c900-012f-314702d1a09a',
 'us-east-1:db841a21-c453-cdbf-70fc-6f564b5574dc',
 'us-east-1:db841a21-c454-c3ab-7175-9d2b3a5f1bba',
 'us-east-1:db841a21-c454-c584-4d11-aa1ddcba6a81',
 'us-east-1:db841a21-c455-c651-3c1e-d6f23adc585c',
 'us-east-1:db841a21-c455-c8ed-7ad2-5d7b62977a18',
 'us-east-1:db841a21-c456-c39a-2aaf-dd7212a0de33',
 'us-east-1:db841a21-c456-c8b4-f98e-3dfdd3f9c3b1',
 'us-east-1:db841a21-c456-ce96-359d-7f4d94e2c931',
 'us-east-1:db841a21-c458-c0ae-3cfe-6a44bc5aaae7',
 'us-east-1:db841a21-c458-c0b3-f9c9-1e6059e31f9e',
 'us-east-1:db841a21-c458-c0bf-e404-c764cda6d9e0',
 'us-east-1:db841a21-c458-cb33-bfd8-eb1bfaa74c84',
 'us-east-1:db841a21-c458-cc9c-e8e4-5884fc04f362',
 'us-east-1:db841a21-c459-c2a9-3738-6149b077089d',
 'us-east-1:db841a21-c459-c983-4892-4743ec7003b9',
 'us-east-1:db841a21-c45a-caad-ad05-e29330c91054',
 'us-east-1:db841a21-c45a-cdb3-b7ac-8e4c3bf00f7a',
 'us-east-1:db841a21-c45b-c260-4719-054cd2504f18',
 'us-east-1:db841a21-c45b-c4c3-6070-69e96f43b266',
 'us-east-1:db841a21-c45b-cd69-91cf-5c81af2a5c6f',
 'us-east-1:db841a21-c45c-c668-6a62-3205af34c064',
 'us-east-1:db841a21-c45c-cea4-81fd-bd8fbf339370',
 'us-east-1:db841a21-c45c-cff5-5078-3442f7e8347a',
 'us-east-1:db841a21-c45d-c5c1-bc06-d92af81b2617',
 'us-east-1:db841a21-c45d-cd96-2c45-eb9eb409117f',
 'us-east-1:db841a21-c45e-c0d7-2a10-cede1a91947e',
 'us-east-1:db841a21-c45e-c14a-015f-ebffd95c48b9',
 'us-east-1:db841a21-c45e-c357-9a9f-48aa3c798e93',
 'us-east-1:db841a21-c45e-c60c-c291-1239df70541e',
 'us-east-1:db841a21-c45e-ccb6-fc43-bef713f23a97',
 'us-east-1:db841a21-c45e-cd79-8492-1a39ee0eddd0',
 'us-east-1:db841a21-c460-c897-327d-30d757f2ae1e',
 'us-east-1:db841a21-c460-cae3-66fd-30fa83d2a609',
 'us-east-1:db841a21-c461-c94a-62d2-412b4d42d028',
 'us-east-1:db841a21-c461-cfbe-ee47-6ada7bfaad51',
 'us-east-1:db841a21-c462-c7e9-9962-5fa6c1cbe047',
 'us-east-1:db841a21-c462-cb37-fcc7-3342adbf8ff1',
 'us-east-1:db841a21-c463-c00d-fbe0-780c388ba581',
 'us-east-1:db841a21-c463-c420-cbc8-c6faeef3519b',
 'us-east-1:db841a21-c463-c47f-6bde-f721b5756731',
 'us-east-1:db841a21-c463-c546-31b2-dea79454af0a',
 'us-east-1:db841a21-c463-cbe9-effe-4ef8724d1fd8',
 'us-east-1:db841a21-c464-c312-e3af-65dd6cdef14d',
 'us-east-1:db841a21-c464-c490-1ea5-5e610f03bd4c',
 'us-east-1:db841a21-c464-c690-1fd9-33ba6bfa6354',
 'us-east-1:db841a21-c464-cfa1-c195-afde81223534',
 'us-east-1:db841a21-c465-c7a6-4867-90f361bc6659',
 'us-east-1:db841a21-c465-c92b-dd2e-3ad9d0502984',
 'us-east-1:db841a21-c465-cb2c-61bd-543dac134875',
 'us-east-1:db841a21-c466-c12b-2876-8fa960982a83',
 'us-east-1:db841a21-c467-c2d7-074c-df3c4de74e25',
 'us-east-1:db841a21-c467-c8e5-c398-edcda24792a7',
 'us-east-1:db841a21-c467-cd0e-cdf7-4698dd7bbfb0',
 'us-east-1:db841a21-c468-c57b-172b-2b9c75031f10',
 'us-east-1:db841a21-c469-c3ab-af66-45b4c5d64760',
 'us-east-1:db841a21-c469-c41e-5923-6d1b98fa4155',
 'us-east-1:db841a21-c469-c7f1-a7dd-c5e17573544d',
 'us-east-1:db841a21-c46a-c6fd-ca13-1faabac2c46d',
 'us-east-1:db841a21-c46a-c859-6e0d-49d4a7416f05',
 'us-east-1:db841a21-c46a-c8a6-6ba4-c98995d2274a',
 'us-east-1:db841a21-c46a-c9ca-72c1-0a4ce2375c47',
 'us-east-1:db841a21-c46a-cf58-49cb-134a9f0f83be',
 'us-east-1:db841a21-c46b-c053-43bb-1abd43ab596d',
 'us-east-1:db841a21-c46b-c8bc-c0f1-57892d09a409',
 'us-east-1:db841a21-c46b-c9fc-ba1c-420b5c8a8fc7',
 'us-east-1:db841a21-c46b-ceda-9ae2-6c5d9d4acae5',
 'us-east-1:db841a21-c46c-c73b-b4d3-0dffff9a5a74',
 'us-east-1:db841a21-c46d-cfc4-6e9f-0ce25c3d51df',
 'us-east-1:db841a21-c46d-cfe3-b592-42ed3accb288',
 'us-east-1:db841a21-c46e-c402-9d11-79d009410d47',
 'us-east-1:db841a21-c46e-c49a-1e4b-e6640201ee7e',
 'us-east-1:db841a21-c46e-c6ec-7b76-e37f72931136',
 'us-east-1:db841a21-c46e-ceac-2504-efdd1c12bb4e',
 'us-east-1:db841a21-c46f-c218-5087-74584b14aa38',
 'us-east-1:db841a21-c470-c430-bf86-2ca6a47d02ab',
 'us-east-1:db841a21-c470-c9c4-6039-899cda508ab3',
 'us-east-1:db841a21-c470-cee4-7a0e-d346e670d0c8',
 'us-east-1:db841a21-c471-c2ea-4000-67c9b49cc5b2',
 'us-east-1:db841a21-c471-c67b-c25e-728c313ff278',
 'us-east-1:db841a21-c472-c5e0-46b0-8dfd638a3400',
 'us-east-1:db841a21-c473-c7ec-94a8-d4cd06dbb0b9',
 'us-east-1:db841a21-c473-c842-91b3-210ae292eebf',
 'us-east-1:db841a21-c474-c7e3-a0e7-8c04d08e65c5',
 'us-east-1:db841a21-c474-c8c5-09e1-3b7f227477a9',
 'us-east-1:db841a21-c474-cc30-db25-006da5a9853f',
 'us-east-1:db841a21-c475-c44e-18ef-55341f28bdbc',
 'us-east-1:db841a21-c475-c9bd-7dcd-4922d8a866db',
 'us-east-1:db841a21-c476-c219-cfdc-f0d6ab372742',
 'us-east-1:db841a21-c476-c2cb-6dc8-a43ca2710920',
 'us-east-1:db841a21-c476-c40e-cf2e-a1221c19c3e7',
 'us-east-1:db841a21-c476-cc09-653b-8ba972078faf',
 'us-east-1:db841a21-c478-c22f-a6cd-a3d3b72fc439',
 'us-east-1:db841a21-c478-c94f-f4df-d0373452516f',
 'us-east-1:db841a21-c478-cbd9-92c7-ac96d10937bd',
 'us-east-1:db841a21-c479-c516-71ef-936bffe61cf9',
 'us-east-1:db841a21-c479-c9fe-e3e8-7dfe6f10cafe',
 'us-east-1:db841a21-c479-cbb8-4e66-a0858553b138',
 'us-east-1:db841a21-c479-cec1-348d-1d4cf0da1d8e',
 'us-east-1:db841a21-c47a-c5e5-13d0-d16b8887983b',
 'us-east-1:db841a21-c47b-c2e4-b6ed-c1ae4dad13ff',
 'us-east-1:db841a21-c47b-ccbf-3187-ecadb28f5624',
 'us-east-1:db841a21-c47d-c6e9-48da-980b0f23abef',
 'us-east-1:db841a21-c47d-c75c-0caa-1c49817a55b8',
 'us-east-1:db841a21-c47d-ca44-d68f-255ff83d636c',
 'us-east-1:db841a21-c47e-ca4f-4311-0cdd70ad35f1',
 'us-east-1:db841a21-c47e-cbec-223e-8822146794d9',
 'us-east-1:db841a21-c47e-cfab-1ebe-8283ed8dfd96',
 'us-east-1:db841a21-c481-c824-6066-c6f99e4dfc87',
 'us-east-1:db841a21-c482-c34c-9e7d-9e848b4feaf0',
 'us-east-1:db841a21-c482-c50f-0544-56c932377c1d',
 'us-east-1:db841a21-c483-c023-7394-7e7298192189',
 'us-east-1:db841a21-c483-c211-3c17-7d1d00c02b04',
 'us-east-1:db841a21-c483-c43c-9f0a-fe88037847ec',
 'us-east-1:db841a21-c483-c46d-3240-5dd41ffcae5d',
 'us-east-1:db841a21-c483-ccdf-7486-5c8557323cf6',
 'us-east-1:db841a21-c484-cbbd-91c7-c790dee67b05',
 'us-east-1:db841a21-c485-cd9e-ef3f-f2372b62a6be',
 'us-east-1:db841a21-c486-c056-ff2d-bff2e2b29e3c',
 'us-east-1:db841a21-c486-c6ab-3f1e-2bb727909595',
 'us-east-1:db841a21-c486-cb21-0f3e-e728b484954b',
 'us-east-1:db841a21-c486-cc26-8e1b-9b9909da55f5',
 'us-east-1:db841a21-c486-cc37-3a3a-dc725a3378ac',
 'us-east-1:db841a21-c487-c103-16d9-9142789132a0',
 'us-east-1:db841a21-c487-c6b0-338c-4e7d4ea20ed8',
 'us-east-1:db841a21-c489-c1a1-6a60-77bb9da71e14',
 'us-east-1:db841a21-c489-c3de-8915-8f6e0625a820',
 'us-east-1:db841a21-c489-cbef-d47e-4b22adcbb520',
 'us-east-1:db841a21-c489-cdec-ce49-0b80627ef1ea',
 'us-east-1:db841a21-c48b-c98d-45f2-853d66a8eca7',
 'us-east-1:db841a21-c48b-cd1c-563f-eb23aa6c2768',
 'us-east-1:db841a21-c48b-ce33-e1b5-77065d0a6cdf',
 'us-east-1:db841a21-c48c-c5b2-5df3-dffbb168b121',
 'us-east-1:db841a21-c48c-ce55-3d83-34443699079c',
 'us-east-1:db841a21-c48d-c341-ac23-33c8900931e6',
 'us-east-1:db841a21-c48d-c70e-7c24-caa38c0298c0',
 'us-east-1:db841a21-c48d-c8ef-6170-bc1c52a15da5',
 'us-east-1:db841a21-c48e-c621-2162-60e0f4567726',
 'us-east-1:db841a21-c48e-c81d-5791-d71ba86472fc',
 'us-east-1:db841a21-c48f-c8bd-70f8-85522fc7a0cc',
 'us-east-1:db841a21-c48f-ca14-2d17-bec010976072',
 'us-east-1:db841a21-c490-c06d-9ebf-b3c34c4f53cd',
 'us-east-1:db841a21-c490-c6c4-f359-1137dc188ac4',
 'us-east-1:db841a21-c491-c3ff-872b-82f5dcba616d',
 'us-east-1:db841a21-c491-c863-4998-71ad846ad6bc',
 'us-east-1:db841a21-c492-c00a-c53d-49fc76dbc4cc',
 'us-east-1:db841a21-c492-c0a7-076a-074dbd9ae4ba',
 'us-east-1:db841a21-c492-c0eb-a894-64efda6db1c6',
 'us-east-1:db841a21-c493-c3ff-f24d-adb71eccf341',
 'us-east-1:db841a21-c493-cdce-afd9-491ce56f3dfa',
 'us-east-1:db841a21-c494-c671-d7ab-063a3185dcf8',
 'us-east-1:db841a21-c494-c86e-a6f0-50ff0702662d',
 'us-east-1:db841a21-c494-c8ab-0748-745160c49384',
 'us-east-1:db841a21-c494-cf20-c1f5-ddec795b01a3',
 'us-east-1:db841a21-c495-c849-d83a-8eeb9d506ba6',
 'us-east-1:db841a21-c495-cb36-bdd8-622770e67413',
 'us-east-1:db841a21-c495-cb90-fd06-c79d26b3ec49',
 'us-east-1:db841a21-c496-c0ac-b6b4-a56c1eec83dc',
 'us-east-1:db841a21-c496-c491-5dd4-2e154196a063',
 'us-east-1:db841a21-c496-c52d-d7c1-dfd1ae2164bd',
 'us-east-1:db841a21-c497-c19b-4c1f-312ccdf39210',
 'us-east-1:db841a21-c497-c68b-e47a-c293a1beb2ba',
 'us-east-1:db841a21-c498-c369-ba39-d9ad87215ff7',
 'us-east-1:db841a21-c498-c6cc-bc93-75c30d8c66a9',
 'us-east-1:db841a21-c498-c7b5-df83-c83f0c31d75c',
 'us-east-1:db841a21-c498-c7b6-a37f-6ce5c5a84dad',
 'us-east-1:db841a21-c498-c814-4d4d-32e1c1d3c22b',
 'us-east-1:db841a21-c49a-cd19-5574-e92f8666dcb2',
 'us-east-1:db841a21-c49b-c76d-a9bf-4edf07b708e3',
 'us-east-1:db841a21-c49b-c9cd-33d4-e475588cadb0',
 'us-east-1:db841a21-c49b-ca54-cca1-95ac3d061acf',
 'us-east-1:db841a21-c49b-cc26-6930-c2931c56f3b3',
 'us-east-1:db841a21-c49b-cfd2-aae8-9fe36d53e0fc',
 'us-east-1:db841a21-c49d-c643-8b84-f441def3d40a',
 'us-east-1:db841a21-c49d-c770-87a6-ba02c9fdd888',
 'us-east-1:db841a21-c49d-ca25-e804-b116daffd4b0',
 'us-east-1:db841a21-c49e-c703-10c5-00e249b0514d',
 'us-east-1:db841a21-c49e-c931-7b51-57fde617ab2a',
 'us-east-1:db841a21-c49f-c09d-8eb2-fc10f01b3ea1',
 'us-east-1:db841a21-c49f-c320-0fd6-1af1dbe2dacf',
 'us-east-1:db841a21-c49f-c6c6-0e09-8d9ac9a422f1',
 'us-east-1:db841a21-c49f-c760-931e-edad68405aba',
 'us-east-1:db841a21-c4a0-c8f9-84f7-486a6b5ffcad',
 'us-east-1:db841a21-c4a1-c09a-71a3-1a25f8ccc7d8',
 'us-east-1:db841a21-c4a1-c482-21b4-e14988013ca0',
 'us-east-1:db841a21-c4a2-c63d-d1b7-cca9b6a94c3b',
 'us-east-1:db841a21-c4a2-c656-defe-771c4a10b19a',
 'us-east-1:db841a21-c4a2-cdcf-0452-3032b8f32861',
 'us-east-1:db841a21-c4a3-c163-5af2-67f18c61c6ff',
 'us-east-1:db841a21-c4a4-c174-bbca-21281c7a35cb',
 'us-east-1:db841a21-c4a4-c45c-f777-8ec056a4d5ab',
 'us-east-1:db841a21-c4a5-c281-441e-c49658f55f83',
 'us-east-1:db841a21-c4a5-c2c4-b5b3-82b12343a747',

In [74]:
len(problematic_users_sleep)

591

In [78]:
df.head()

,user_id,ts,active_time_m7,active_time_m14,active_time_s7,active_time_s14,activity_percent_m7,activity_percent_m14,activity_percent_s7,activity_percent_s14,...,phq9_total,deployment,age_binary,missing_Sleep,missing_Activity,missing_Sociability,missing_Device Usage,missing_Demographic,missing_Other,missing_Target
0,us-east-1:db841a21-c4fd-cf09-4379-5af0b6185e0e,2024-03-23 21:58:52.242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,hr-ascent-1,old,True,True,True,True,True,True,False
1,us-east-1:db841a21-c48b-cd1c-563f-eb23aa6c2768,2024-03-26 14:46:43.386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,hr-ascent-1,young,True,True,True,True,True,True,False
2,us-east-1:db841a21-c46a-c6fd-ca13-1faabac2c46d,2024-03-27 16:19:40.526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,hr-ascent-1,old,True,True,True,True,True,True,False
3,us-east-1:db841a21-c4b2-c6b9-91ed-370b2da2aa86,2024-03-27 16:42:15.485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.0,hr-ascent-1,young,True,True,True,True,True,True,False
4,us-east-1:db841a21-c438-c76a-5078-c47a75e6b0c3,2024-03-28 14:52:36.017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,hr-ascent-1,young,True,True,True,True,True,True,False

In [105]:
feature_buckets.keys()

dict_keys(['Sleep', 'Activity', 'Sociability', 'Device Usage', 'Demographic', 'Other', 'Target'])

In [106]:
critical_features = feature_buckets['Sleep'] + feature_buckets['Activity'] + feature_buckets['Sociability'] 
critical_features

['sleep_duration_m7',
 'sleep_duration_m14',
 'sleep_duration_s7',
 'sleep_duration_s14',
 'sleep_start_m7',
 'sleep_start_m14',
 'sleep_start_s7',
 'sleep_start_s14',
 'sleep_end_m7',
 'sleep_end_m14',
 'sleep_end_s7',
 'sleep_end_s14',
 'sleep_interruptions_m7',
 'sleep_interruptions_m14',
 'sleep_interruptions_s7',
 'sleep_interruptions_s14',
 'sleep_routine_index_m7',
 'sleep_routine_index_m14',
 'sleep_routine_index_s7',
 'sleep_routine_index_s14',
 'chronotype_score_m7',
 'chronotype_score_m14',
 'chronotype_score_s7',
 'chronotype_score_s14',
 'active_time_m7',
 'active_time_m14',
 'active_time_s7',
 'active_time_s14',
 'activity_percent_m7',
 'activity_percent_m14',
 'activity_percent_s7',
 'activity_percent_s14',
 'ec_Activity_m7',
 'ec_Activity_m14',
 'ec_Activity_s7',
 'ec_Activity_s14',
 'ec_PedometerData_m7',
 'ec_PedometerData_m14',
 'ec_PedometerData_s7',
 'ec_PedometerData_s14',
 'step_count_m7',
 'step_count_m14',
 'step_count_s7',
 'step_count_s14',
 'steps_most_active_10h_m7',
 'steps_most_active_10h_m14',
 'steps_most_active_10h_s7',
 'steps_most_active_10h_s14',
 'steps_least_active_5h_m7',
 'steps_least_active_5h_m14',
 'steps_least_active_5h_s7',
 'steps_least_active_5h_s14',
 'steps_relative_amplitude_m7',
 'steps_relative_amplitude_m14',
 'steps_relative_amplitude_s7',
 'steps_relative_amplitude_s14',
 'walking_rate_m7',
 'walking_rate_m14',
 'walking_rate_s7',
 'walking_rate_s14',
 'total_activity_duration_m7',
 'total_activity_duration_m14',
 'total_activity_duration_s7',
 'total_activity_duration_s14',
 'time_at_home_m7',
 'time_at_home_m14',
 'time_at_home_s7',
 'time_at_home_s14',
 'time_at_location_1_m7',
 'time_at_location_2_m7',
 'time_at_location_3_m7',
 'time_at_location_4_m7',
 'time_at_location_5_m7',
 'time_at_location_1_m14',
 'time_at_location_2_m14',
 'time_at_location_3_m14',
 'time_at_location_4_m14',
 'time_at_location_5_m14',
 'time_at_location_1_s7',
 'time_at_location_2_s7',
 'time_at_location_3_s7',
 'time_at_location_4_s7',
 'time_at_location_5_s7',
 'time_at_location_1_s14',
 'time_at_location_2_s14',
 'time_at_location_3_s14',
 'time_at_location_4_s14',
 'time_at_location_5_s14',
 'num_location_clusters_m7',
 'num_location_clusters_m14',
 'num_location_clusters_s7',
 'num_location_clusters_s14',
 'loc_entropy_m7',
 'loc_entropy_m14',
 'loc_entropy_s7',
 'loc_entropy_s14',
 'travel_diameter_m7',
 'travel_diameter_m14',
 'travel_diameter_s7',
 'travel_diameter_s14',
 'ec_Location_m7',
 'ec_Location_m14',
 'ec_Location_s7',
 'ec_Location_s14',
 'total_location_duration_m7',
 'total_location_duration_m14',
 'total_location_duration_s7',
 'total_location_duration_s14']

In [107]:
# Select critical features (e.g., all sleep-related columns)
#critical_features = feature_buckets['sleep'] + feature_buckets['travel'] + [...]  # Customize

# Compute missingness for each feature
missing_by_feature = df.groupby('user_id')[critical_features].apply(
    lambda x: x.isnull().mean()
).reset_index()
missing_by_feature

,user_id,sleep_duration_m7,sleep_duration_m14,sleep_duration_s7,sleep_duration_s14,sleep_start_m7,sleep_start_m14,sleep_start_s7,sleep_start_s14,sleep_end_m7,...,travel_diameter_s7,travel_diameter_s14,ec_Location_m7,ec_Location_m14,ec_Location_s7,ec_Location_s14,total_location_duration_m7,total_location_duration_m14,total_location_duration_s7,total_location_duration_s14
0,us-east-1:db841a21-c400-c09b-cb33-144516a80231,0.333333,0.666667,0.333333,0.666667,0.333333,0.666667,0.333333,0.666667,0.333333,...,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
1,us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,0.166667,0.000000,0.166667,0.000000,0.166667,0.000000,0.166667
2,us-east-1:db841a21-c402-c83f-fadf-41f6d4271053,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000
3,us-east-1:db841a21-c402-c9e0-501c-45fd38e3b5e3,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.500000,0.750000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,us-east-1:db841a21-c4ff-c644-6a64-0583e73a79d9,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.800000,0.800000,0.200000,0.200000,0.200000,0.200000,0.200000,0.200000,0.200000,0.200000
597,us-east-1:db841a21-c4ff-c868-02a6-5cfff64a075a,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.333333,0.333333,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
598,us-east-1:db841a21-c4ff-cb45-cad0-4821d631eb58,0.666667,0.833333,0.666667,0.833333,0.666667,0.833333,0.666667,0.833333,0.666667,...,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
599,us-east-1:db841a21-c4ff-cb63-a6da-f45b3c81a5c5,0.333333,0.500000,0.333333,0.500000,0.333333,0.500000,0.333333,0.500000,0.333333,...,0.333333,0.500000,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
600,us-east-1:db841a21-c4ff-cf28-acdc-a8ab36af1fa3,0.166667,0.333333,0.166667,0.333333,0.166667,0.333333,0.166667,0.333333,0.166667,...,0.500000,0.666667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667

In [109]:

# Melt for visualization/analysis
missing_by_feature_melted = missing_by_feature.melt(
    id_vars='user_id', var_name='feature', value_name='missing_proportion'
)
missing_by_feature_melted

,user_id,feature,missing_proportion
0,us-east-1:db841a21-c400-c09b-cb33-144516a80231,sleep_duration_m7,0.333333
1,us-east-1:db841a21-c400-ce85-5cd6-95d896fd3268,sleep_duration_m7,1.000000
2,us-east-1:db841a21-c402-c83f-fadf-41f6d4271053,sleep_duration_m7,1.000000
3,us-east-1:db841a21-c402-c9e0-501c-45fd38e3b5e3,sleep_duration_m7,1.000000
4,us-east-1:db841a21-c402-cf75-e0bb-eec187eb84b1,sleep_duration_m7,1.000000
...,...,...,...
64903,us-east-1:db841a21-c4ff-c644-6a64-0583e73a79d9,total_location_duration_s14,0.200000
64904,us-east-1:db841a21-c4ff-c868-02a6-5cfff64a075a,total_location_duration_s14,0.166667
64905,us-east-1:db841a21-c4ff-cb45-cad0-4821d631eb58,total_location_duration_s14,0.166667
64906,us-east-1:db841a21-c4ff-cb63-a6da-f45b3c81a5c5,total_location_duration_s14,0.166667
64907,us-east-1:db841a21-c4ff-cf28-acdc-a8ab36af1fa3,total_location_duration_s14,0.166667

In [110]:
missing_by_feature_melted[missing_by_feature_melted.user_id == 'us-east-1:db841a21-c400-c09b-cb33-144516a80231']

,user_id,feature,missing_proportion
0,us-east-1:db841a21-c400-c09b-cb33-144516a80231,sleep_duration_m7,0.333333
601,us-east-1:db841a21-c400-c09b-cb33-144516a80231,sleep_duration_m14,0.666667
1202,us-east-1:db841a21-c400-c09b-cb33-144516a80231,sleep_duration_s7,0.333333
1803,us-east-1:db841a21-c400-c09b-cb33-144516a80231,sleep_duration_s14,0.666667
2404,us-east-1:db841a21-c400-c09b-cb33-144516a80231,sleep_start_m7,0.333333
...,...,...,...
61903,us-east-1:db841a21-c400-c09b-cb33-144516a80231,ec_Location_s14,0.166667
62504,us-east-1:db841a21-c400-c09b-cb33-144516a80231,total_location_duration_m7,0.166667
63105,us-east-1:db841a21-c400-c09b-cb33-144516a80231,total_location_duration_m14,0.166667
63706,us-east-1:db841a21-c400-c09b-cb33-144516a80231,total_location_duration_s7,0.166667
64307,us-east-1:db841a21-c400-c09b-cb33-144516a80231,total_location_duration_s14,0.166667